### ISSUE TITLE
Windows Bugs

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#1020]
**Describe the bug**

Looking at [this comment](https://github.com/intuit/auto/issues/973#issuecomment-595064147) I saw the following in the logs

```
‼  warning   Could not find plugin: C:\Users\adam\Developer\design-systems-with-storybook-example\node_modules\@auto-canary\core\dist\plugins\filter-non-pull-request.js
‼  warning   Could not find plugin: npm
```

**To Reproduce**

Run auto commands on a windows machine. Look too referenced comment/issue for repro repo.

**Expected behavior**

All plugins load without warnings.

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.15.11` :rocket:
