### ISSUE TITLE
Publish failing with the following error

### ISSUE THREAD

**Issue by yashug** [intuit/auto#1065]
**Describe the bug**

Error: Working direction is not clean, make sure all files are committed
    at Auto.checkClean (/home/runner/work/*/node_modules/@auto-it/core/dist/auto.js:100:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Auto.publishFullRelease (/home/runner/work/*/node_modules/@auto-it/core/dist/auto.js:892:13)
    at async Auto.shipit (/home/runner/work*/node_modules/@auto-it/core/dist/auto.js:821:27)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment information:**

```txt
```

**Additional context**

**Comment by zephraph** [comment]
Could you add a little more context? It seems like you were trying to do a release when there were changed files. This could happen if your `yarn.lock` file changed during CI for example.

**Comment by hipstersmoothie** [comment]
During any type of publish we ensure that there are no uncommitted files. The error message should include what files are changed though

![Screen Shot 2020-03-17 at 8 51 46 AM](https://user-images.githubusercontent.com/1192452/76874537-8d7f4780-682c-11ea-9dbd-7ac1f6b237fc.png)

you might be on an older version though

**Comment by yashug** [comment]
@zephraph @hipstersmoothie yes, yarn.lock file is changing during CI process. But i pushed latest yarn.lock to master branch. i am not sure why the yarn.lock file changing during CI process. It was working fine before, just observing this behaviour in recent versions. 

i use dependabot to keep update to latest version. so no chance of using older version. 

please help me here

**Comment by hipstersmoothie** [comment]
When in the CI it is recommended to use [`yarn  install --frozen-lockfil`](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-frozen-lockfile).

**Comment by yashug** [comment]
@hipstersmoothie thanks. Will  try and let you know

**Comment by hipstersmoothie** [comment]
@yashug did you resolve this?

**Comment by yashug** [comment]
@hipstersmoothie yes it did. Thank you so much
