### ISSUE TITLE
Append suffix to version tag

### ISSUE THREAD

**Issue by smoia** [intuit/auto#1080]
**Is your feature request related to a problem? Please describe.**

I'm implementing auto in a package I'm managing (issue physiopy/phys2bids#181 ) to create automatic releases with Git Tag (and update Pipy and zenodo). We're still in beta stage, and I was wondering if there is a way to append a suffix to the version tag (e.g. `v1.3.0-beta`) to indicate the development stage. I checked documentation and `auto release` help, and I didn't see it. Sorry if I missed it!

**Comment by hipstersmoothie** [comment]
The way auto supports `beta` release lines is with `next` branches. Basically you just:

- create `next` branch (or configure another name)
- start making PRs into that branch
- when you merge into that branch `shipit` runs and makes a pre-release
- merge `next` into `master` and `auto` publishes all the changes to `latest`

Docs on prereleases: https://intuit.github.io/auto/pages/generated/shipit.html#prereleases

At the top of [this page](https://intuit.github.io/auto/pages/generated/shipit.html) we detail what type of release is made in different situations. The default workflow for `auto` is: run `shipit` at the end of every build and `auto` will make the appropriate release (canary, next, or latest)

There are a few other ways you could do pre-release with `auto` but I recommend this one.

Does that help?

**Comment by smoia** [comment]
Hello @hipstersmoothie, thank you for your reply!
Yes, I saw the possibility of maintaining more than a branch and have beta features, and the possibility of "graduating only with release label".
However, our intentions are a bit different.

We're an open development package, that wants to release and track changes even if we're still in beta stage development. For this reason, the only thing we want to point out is that we are in beta stage, even if technically it's our `latest`.

If I create a branch named `beta` and start PR to that branch, would `auto` release a version trailed with a suffix "-beta" or with a suffix "-next"?

**Comment by hipstersmoothie** [comment]
> If I create a branch named beta and start PR to that branch

you would have to do two things:

1. create `beta` branch
2. add `beta` to [`prereleaseBranches`](https://intuit.github.io/auto/pages/autorc.html#prerelease-branches) in your .autorc

> trailed with a suffix "-beta" or with a suffix "-next"

The suffix is based on the prerelease branch.

- run `shipit` from `next` => suffix `-next`
- run `shipit` from `beta` => suffix `-beta`

**Comment by hipstersmoothie** [comment]
Some example tags: https://github.com/intuit/auto/tags?after=v8.0.0

Releases look somewhat like: https://github.com/intuit/auto/releases?after=v8.0.0 (may have changed a little)
