### ISSUE TITLE
If changed, use latest PR title in release notes and changelog

### ISSUE THREAD

**Issue by smoia** [intuit/auto#1081]
**Is your feature request related to a problem? Please describe.**
I'm not sure whether this is a bug or a feature.
Implementing Auto in a repository (issue physiopy/phys2bids#181 ), we realised that the PR title used to create the changelog and the release notes doesn't match with the current title of our PRs.
This is because we changed the titles recently, to make them more human readable, while the title used in the changelog seems to be the one with which the PR was open.

**Describe the solution you'd like**
It would be great if Auto considered the updated PR title, if it changed since the PR was opened.

**Additional context**
See physiopy/phys2bids#181

**Comment by hipstersmoothie** [comment]
I'll take a look at this. It should use the updated title, but you would have to generate the changelog again.

I've definitely changed titles before though.

**Comment by smoia** [comment]
Thank you @hipstersmoothie .
I was playing with auto while updating the labels of our PRs, and I see that also the labels are not respected (see our chagelog again).

**Comment by hipstersmoothie** [comment]
Not that running from within a PR can give you odd changelog results. Looking into this now. It's cool to see a python project using `auto`!

**Comment by smoia** [comment]
Yes, we're excited too!
I preferred `auto` to other packages because I strongly support the use of labels rather than angular commit conventions and similar!

Once our PR is ready and everything works fine, you can add us as an example of Travis CI configuration and python-based-`auto`-adopting project, if you want!

**Comment by smoia** [comment]
Also, I should specify that the changelog that you see in physiopy/phys2bids#181 was obtained by running auto locally on my computer.

**Comment by hipstersmoothie** [comment]
recreated locally. should have a fix in today

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.21.1` :rocket:
