### ISSUE TITLE
Documentation: how to install and use unofficial plugins with binary bundle

### ISSUE THREAD

**Issue by rbellamy** [intuit/auto#1102]
I am looking to use auto with multiple projects, including maven (which has a plugin) and sbt (which does not). The maven plugin is not considered "official" and therefore will not be bundled with the binary distribution.

**Describe the solution you'd like**
I'd like the documentation to outline the recommended method for installing the unofficial plugins for use by a binary installation of auto.

**Describe alternatives you've considered**
I've considered forking the auto repo and building my own bundle, but that seems like overkill. I also note the `--plugins string[]` command line parameter, but there's no discoverability there (there should maybe be a `--list-plugins` to show what's available) nor does the documentation speak to a method for "loading" auto with an unofficial plugin.

**Additional context**
Also, planning on including auto as a binary in our self-hosted Docker-in-Docker [github-runner](https://github.com/terradatum/github-runner).

**Comment by hipstersmoothie** [comment]
> The maven plugin is not considered "official" and therefore will not be bundled with the binary distribution.

All the plugins that are in this repo are included in the binary version. So this shouldn't be a problem

---

You are right though the path for using "unofficial" plugins isn't too obvious. Off the top of my head the ways you could do it are:

1. Have the plugin file local and committed to the project. Until very recently auto did the same. All you need to do is [write the plugin](https://github.com/intuit/auto/blob/aa923fc19f8d459b818656696be7874ab1dd1eb9/scripts/update-tap.js) and [use it in your autorc](https://github.com/intuit/auto/blob/aa923fc19f8d459b818656696be7874ab1dd1eb9/package.json#L159).
2. Host the plugin on GitHub => Set up your CI to clone unofficial plugins to directory + set the path in your rc
3. If distributed via NPM you could install those plugins with `npm` `npm i -g some-plugin`

I'd probably avoid using the --plugins flag, the `.autorc` does a much better job managing that.

--- 

I haven't tested any of the above but I'll explore if they work/how the DX is. Any suggestions are welcome!

I'll look into adding a `--list-plugins` flag.

**Comment by hipstersmoothie** [comment]
You can now run `auto info --list-plugins` to view available plugins. The docs have also been updated with guidance on usage.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.24.0`](https://github.com/intuit/auto/releases/tag/v9.24.0) :rocket:
