### ISSUE TITLE
honor maven options for maven release plugin

### ISSUE THREAD

**Issue by ncheema** [intuit/auto#1105]
**Is your feature request related to a problem? Please describe.**
Maven builds generally allows a set of maven options to be passed as arguments(such as local maven directory, threads, debug mode, etc). 

**Describe the solution you'd like**
Honor an environment variable (`MAVEN_OPTS`) during build/release execution

**Describe alternatives you've considered**

**Additional context**

**Comment by hipstersmoothie** [comment]
From what I can tell `MAVEN_OPTS` can be set from you scripts right? It doesn't seem like you have to do anything extra for the `mvn` command to use that. We already expose the environment to the command so it might already be happening.

Is this request to have some configuration option like 

```json
{
  "plugins": [
    ["maven", { "opts": "-Xms512m -Xmx1024m" }],
  ]
}
```

Or is the request just to *use* the env var when running `mvn`?

**Comment by vaggarwal2** [comment]
@hipstersmoothie @ncheema  I would like to work on this as part of Hacktoberfest. Could you please elaborate on whats expected?

**Comment by hipstersmoothie** [comment]
I think this has already been accomplished
