### ISSUE TITLE
shipit should have a only-publish-with-release-label command-line paramater

### ISSUE THREAD

**Issue by rbellamy** [intuit/auto#1107]
Currently, there are two booleans that dictate how `shipit` behaves during a release:
`onlyGraduateWithReleaseLabel` - default `false`. Used only by `shipit`. Available as a command-line parameter.
`onlyPublishWithReleaseLabel` - default `true` Used by both `version` and `shipit`, but `shipit` doesn't have this command-line switch.

**Comment by hipstersmoothie** [comment]
Oops! Forgot to expose that as a flag (everything else was already hooked up). This is one that I would also probably set in the `.autorc` as some other parts of auto look at this config option.

Thanks for filing these issues!

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.25.0`](https://github.com/intuit/auto/releases/tag/v9.25.0) :rocket:

**Comment by rbellamy** [comment]
Thanks for the quick turnaround!
