### ISSUE TITLE
Support running the tool without an .autorc file to allow changes in configuration at runtime

### ISSUE THREAD

**Issue by rbellamy** [intuit/auto#1116]
**Is your feature request related to a problem? Please describe.**

As it stands today, there are some configuration parameters for the core commands that rely on the results of an inspection of the environment, either via the `.autorc` or the package management control files.

However, these core command parameters have no associated command-line representation.

In other words, I can run the tool with only an `.autorc` file and no command-line parameters. I cannot run the tool with only command-line parameters.

This means that there are some configurations that cannot be changed at runtime, which is problematic when trying to automate the execution of the tool.

See #1113 as an example. Even though `name` and `email` are critical to the execution of `shipit` they are only settable via some file artifact.

**Describe the solution you'd like**

Have a command-line parameter for all required configuration settings for each command.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.26.0`](https://github.com/intuit/auto/releases/tag/v9.26.0) :rocket:
