### ISSUE TITLE
All Contributors: Add contributions in the PR

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#1147]
**Is your feature request related to a problem? Please describe.**

Manage non-code contributions.

**Describe the solution you'd like**

Parse non-code contributions from the PR body

```
# New Contributions
- Some Guy (@some_guy) - design, doc
```

We could also automate a comment so that the person opening the PR knows if the Contributions have been parsed. 

**Describe alternatives you've considered**

Manually running the command 🤮

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.27.0`](https://github.com/intuit/auto/releases/tag/v9.27.0) :rocket:
