### ISSUE TITLE
--quiet flag

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#1154]
**Is your feature request related to a problem? Please describe.**

Sometimes I only want auto to output the result of an operation so I can use it in other scripts.

**Describe the solution you'd like**

1. `auto canary --quiet` - output only the canary version(s) published
2. `auto changelog --quiet` - output only the changelog
3. `auto latest --quiet` - output only the version(s) published
4. `auto next --quiet` - output only the next version(s) published
4. `auto shipit --quiet` - output only the version(s) published

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.28.0`](https://github.com/intuit/auto/releases/tag/v9.28.0) :rocket:
