### ISSUE TITLE
Potential v10 Breaking Changes

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#1156]
This is a tracking issue for things that could change in v10:

- ~Call canary/next hooks even for dry-runs, plugins handle it, enables better --dry-run and --quiet output. [bad code](https://github.com/intuit/auto/pull/1155/files#diff-54899627ccbe2e33cc90970d5e6d5191R1119)~
- ~rename `afterAddToChangelog` to `afterChangelog` since a changelog might not be committed~
- ~make renderChangelogLine waterfall not have to return tuple, it can just return the line~
- context in hooks - all hooks second arg should just be a context object so adding/breaking things isn't too much of a problem
- ~git reset after `canary` and `next` hooks. These should not leave any traces of the last published version other than tags for `next`~

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.0.0-next.2`](https://github.com/intuit/auto/releases/tag/v10.0.0-next.2) :rocket:

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.0.0`](https://github.com/intuit/auto/releases/tag/v10.0.0) :rocket:
