### ISSUE TITLE
Question - lerna ERR! ENOGIT Detached git HEAD within Gitlab CI

### ISSUE THREAD

**Issue by jdalrymple** [intuit/auto#1157]
**Describe the bug**

When running shipit, lerna errors out on the last [step](https://gitlab.com/jdalrymple/gitbeaker/-/jobs/517564586#L96)

This might be more related to lerna, as ive seen the errors reported a few times, but I was wondering if you guys had any suggestions since the lerna call is within auto?

*EDIT*: Testing locally returns different errors. Going to look into that further and followup!

**Comment by jdalrymple** [comment]
Seems to work fine when ran locally, just not in the ci environment. hmm

**Comment by hipstersmoothie** [comment]
First, IDK how well auto can possibly work with GitLab since we *heavily* use the GitHub API. Things like looking up the pull requests, making releases, and a whole host of other things won't work as expected.

---

As for the detached head issue: Most CI envs do not checkout your code in the same way. For `auto` to work it needs a relatively complete view of the git repo. Many CI envs try to be smart and not do a full checkout. Some will do a shallow clone (github actions). Some will pre-merge your branch and checkout a tmp branch (jenkins)

Looking at your logs it seems like GitLab does a relatively full checkout,  but with detached head (you aren't on a branch). Try checking out `master`.


```sh
# See what branches are available
git branch -a

# Checkout master
git checkout master
```

**Comment by jdalrymple** [comment]
That seemed to fix that error, but now it isnt releasing due to [this](https://gitlab.com/jdalrymple/gitbeaker/-/jobs/517741900#L93) :cry:

**Comment by jdalrymple** [comment]
Did a quick search but i cant seem to figure out what causes that error message.

**Comment by hipstersmoothie** [comment]
That error comes from `auto`

https://github.com/intuit/auto/blob/adf4e85590a75a9fd97945b4803f3535b8c45383/packages/core/src/auto.ts#L405

It might be swallowing another error though. I can add a log to print in this function if you need it

**Comment by jdalrymple** [comment]
:facepalm: not sure how i missed that. Ill just modify my local node_module to see if i can see the swallowed error. Ill follow up after! Thank you for pointing it out

**Comment by hipstersmoothie** [comment]
https://github.com/intuit/auto/pull/1159

**Comment by jdalrymple** [comment]
Is it possible the `-silent` flag should be `--silent` ? 

https://gitlab.com/jdalrymple/gitbeaker/-/jobs/518962749#L1391

**Comment by hipstersmoothie** [comment]
Oh man 🤦 I must have deleted a `-`

https://github.com/intuit/auto/pull/1160

**Comment by hipstersmoothie** [comment]
New features can be buggy 😓 Next release should have fixed the --quiet flag

**Comment by hipstersmoothie** [comment]
Once this publishes it should be good https://github.com/intuit/auto/pull/1161/files

**Comment by jdalrymple** [comment]
Another problem fixed butttt [hehe](https://gitlab.com/jdalrymple/gitbeaker/-/jobs/519038782#L1456) Any other suggestions?

**Comment by hipstersmoothie** [comment]
You seem to still be on an old canary `"auto" version: v9.28.2-canary.1160.15021.0` and not the last released version

**Comment by jdalrymple** [comment]
Oops! just fixed that. Still having [bad luck](https://gitlab.com/jdalrymple/gitbeaker/-/jobs/519270236#L1591) :( Now with  Error: Command failed: git merge-base --is-ancestor :cry:

**Comment by jdalrymple** [comment]
Hmm reading over the logs again, is it possible its using the wrong [remote url](https://gitlab.com/jdalrymple/gitbeaker/-/jobs/520010730#L223)?

` ℹ  info      Using remote: https://gitlab-ci-token:[MASKED]@gitlab.com/jdalrymple/gitbeaker.git`

**Comment by jdalrymple** [comment]
So i worked a way around this error by explicitly setting the remote url. Kinda of hacky, but it would work for now. Trying to fix a weird npm error [now](https://gitlab.com/jdalrymple/gitbeaker/-/jobs/520263409#L9241). So close :/

**Comment by jdalrymple** [comment]
It worked!!! Had to explicitly set some things but yay! Thanks for the help!!

**Comment by hipstersmoothie** [comment]
Building on GitLab is probably the source of most of these problems. As you found with the remote CI services tend to make a bunch of different assumptions. 

That said we might be able to improve the remote logic and detect when we are on gitlab CI. 

Here is where you would change the code to figure out the remote https://github.com/intuit/auto/blob/master/packages/core/src/auto.ts#L556

**Comment by jdalrymple** [comment]
> It is supposed to create the github release also. I'll look into what you've posted. We can dm on twitter if you want quicker responses too

Ill make a another release in about 10 min so you can see what ends up happening, but the last release that was made i had to manually add the github release notes.

**Comment by hipstersmoothie** [comment]
can you get me the full log for that? I'm looking at one now but it truncates

https://storage.googleapis.com/gitlab-gprd-artifacts/f8/ab/f8ab07c2ce3c8a4bb3a9aaeebf31a988f9b5635c0675940782abde05ff493a87/2020_04_21/520424876/564920430/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&GoogleAccessId=gitlab-object-storage-prd@gitlab-production.iam.gserviceaccount.com&Signature=MrfCZbFR5Fhfpi7n4rugDcPNrnBMwA3bS69gC%2FVIvjq74AFzWqoD3Egi3xzw%0AJ6xy%2B6HNyfRx3y%2Fg%2BJtCcGgNveTPkWnr6RcgFy63D4qRcUlG0dVVkg1PB0xC%0AkkB9k2jIHiZ26WyVM0LRDIcxmn2uRh8XeXylMjEHQoTOhiyouf1SufSQNiIJ%0A4d8QkK8PsKuK1LZ53gU9ChlORRhC3dBxY7wrM1FG9WjrUKNqLRplVJSDAGCT%0ANLFid313aRu1%2BiIxSLRlDexPjrKHsL2D%2FKHJOYMyt7Jb0y41qJVdIwu%2FrPqO%0ACEAQ5Kj9J%2BXFrhs%2FiiMhfMaU%2FMpNAcyh0WuATpCoMA%3D%3D&Expires=1587495568

**Comment by hipstersmoothie** [comment]
I think you need to up the `output_limit` https://docs.gitlab.com/runner/configuration/advanced-configuration.html

**Comment by jdalrymple** [comment]
Looking into modifying that limit now. It looks like it errors when trying to get the [git log](https://gitlab.com/jdalrymple/gitbeaker/-/jobs/520365119#L10538) AH, it is using a tag with the prefix 'v' but my lerna config excludes the prefix? 

```
ℹ  info      Using 17.0.3 as previous release.
ℹ  info      Current "Latest Release" on Github: v17.0.3
ℹ  info      Getting commits from v17.0.3 to HEAD
```

shouldnt it be looking for commits from the tag to head, so in this case 17.0.3 to HEAD?

**Comment by hipstersmoothie** [comment]
This is because auto defaults to `v` prefixes. I just opened a PR that will make auto respect the lerna config 

https://github.com/intuit/auto/pull/1170

**Comment by hipstersmoothie** [comment]
You could also just set `noVersionPrefix` in your auto config. but I think automating this is better

**Comment by jdalrymple** [comment]
> You could also just set `noVersionPrefix` in your auto config. but I think automating this is better

Would that be the better way to define that configuration? Probably eh?

**Comment by hipstersmoothie** [comment]
The thing is you would also have to set the lerna config too

https://github.com/intuit/auto/pull/1170

I made it automatic so you should just need to upgrade auto

**Comment by hipstersmoothie** [comment]
You might need to edit the last tag/release to not have the `v` prefix

**Comment by jdalrymple** [comment]
Ill check that! thanks!
