### ISSUE TITLE
Avoid commenting on PR if --pr flag is not provided

### ISSUE THREAD

**Issue by kevinwolfdev** [intuit/auto#1190]
**Describe the bug**

While trying to release to canary from my default branch, I am receiving an error:

```
Could not detect PR number. pr-body must be run from either a PR or have the PR number supplied via the --pr flag.
```

**To Reproduce**

1. Create a new repo
2. Configure the CI to run `auto canary` instead of `auto shipit`
3. Commit and push something to `master`.

**Expected behavior**

What I expect is only a normal release, without attempting to comment on the PR.

**Screenshots**

N/A

**Environment information:**

```txt
Environment Information:

"auto" version: v9.30.4
"git"  version: v2.24.2 (Apple Git-127)
"node" version: v14.0.0

Project Information:

✔ Repository:      kevinwolfdev/auto-test (​https://github.com/kevinwolfdev/auto-test​)
✔ Author Name:     Kevin Wolf
✔ Author Email:    hi@kevinwolf.dev
✔ Current Version: v0.0.1-canary.undefined.a1a61ca.0
✖ Latest Release:  

✖ Labels configured on GitHub project (Try running "auto create-labels")

GitHub Token Information:

✔ Token:            [Token starting with c2c7]
✔ Repo Permission:  admin
✔ User:             kevinwolfdev
✔ API:              https://api.github.com (​https://api.github.com​)
✔ Enabled Scopes:   repo
✔ Rate Limit:       4979/5000
```

**Additional context**

I am working on a library in which I want to be releasing small canary features rather than releasing to `latest` channel, and once it is on a good shape, release to `1.0.0`

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.30.5`](https://github.com/intuit/auto/releases/tag/v9.30.5) :rocket:
