### ISSUE TITLE
Option to skip Changelog step on shipit command

### ISSUE THREAD

**Issue by brunobertoldi** [intuit/auto#1192]
**Is your feature request related to a problem? Please describe.**

No, it's just an option to skip Changelog generation and maybe other `shipit` steps.
In some workflows, it would keep the `master` branch history clean and the branches up-to-date.

**Describe the solution you'd like**

IMHO, a [flag on shipit command](https://intuit.github.io/auto/pages/generated/shipit.html#options) would be the easiest way to skip the Changelog step.
I could implement it, but I don't know if it's compatible with the current design.

**Describe alternatives you've considered**

In addition to the alternative above, I've considered:

1. Using [Exec](https://intuit.github.io/auto/plugins/exec/README.html) plugin to override `onCreateChangelog` or `beforeCommitChangelog`
1. Scripting `shipit` manually with commands `version`, `release`, `next` and trigger the plugins (but it may be insufficient or cumbersome)

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.31.0`](https://github.com/intuit/auto/releases/tag/v9.31.0) :rocket:
