### ISSUE TITLE
Support .autorc.js config file

### ISSUE THREAD

**Issue by bmuenzenmeyer** [intuit/auto#1234]
**Is your feature request related to a problem? Please describe.**

[Cosmiconfig](https://github.com/davidtheclark/cosmiconfig#readme) supports javascript config files, but [auto is limited in its search places](https://github.com/intuit/auto/blob/master/packages/core/src/config.ts#L67-L73). It's nice to have comments (superior to `.json`) and logic if needed. 

**Describe the solution you'd like**

I want to configure auto using an `.autorc.js` file.
Cosmiconfig also supports a `.config.js` CommonJS module

**Describe alternatives you've considered**

I first started with `.autorc`, then moved to `.autorc.yml` (for better readability / comments), and finally to `.autorc.json`(because whitespace shouldnt mean something, IMO).

**Additional context**

I am interested in contributing this functionality if accepted.

**Comment by hipstersmoothie** [comment]
@zephraph What was the reason we disallowed `.autorc.js`? Some limitation of GitHub app right? maybe we should allow `.js` and if they want to use autobot then must switch to another format.

**Comment by zephraph** [comment]
Yeah, the purpose was really because js files aren’t statically analyzable in the same way. 

I’m 👍 if you want to re-enable that though.

**Comment by bmuenzenmeyer** [comment]
yea someone could easily use `require` or `import` within one, complicating life I suppose (part of the draw too, IMO)

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.34.0`](https://github.com/intuit/auto/releases/tag/v9.34.0) :rocket:
