### ISSUE TITLE
Question: How to use in non-js settings?

### ISSUE THREAD

**Issue by kai-tub** [intuit/auto#1237]
Hi,

First of all, this package looks amazing!
But I am not sure how well it fits my needs.
What I can tell from the documentation it does everything I would like to do (a lot more than that),
but I've never worked with JS and NPM. I am using GitHub actions as a CI/CD pipeline for my project: a GitHub action, which is nothing more than a shell script.

After running `auto init` I got my configured `.autorc` file. I've included the installation of `auto-it/git-tag` to my yml file, as I need it to calculate the next release tag.
I get the following error:

```
✖  error     Changed Files:
 ?? node_modules/
?? package.json
?? yarn.lock
Error: Working directory is not clean, make sure all files are committed
    at Auto.checkClean (/home/runner/.npm/_npx/2697/lib/node_modules/auto/node_modules/@auto-it/core/dist/auto.js:102:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Auto.publishFullRelease (/home/runner/.npm/_npx/2697/lib/node_modules/auto/node_modules/@auto-it/core/dist/auto.js:986:13)
    at async Auto.shipit (/home/runner/.npm/_npx/2697/lib/node_modules/auto/node_modules/@auto-it/core/dist/auto.js:915:27)
    at async run (/home/runner/.npm/_npx/2697/lib/node_modules/auto/dist/run.js:69:17)
    at async Object.main [as default] (/home/runner/.npm/_npx/2697/lib/node_modules/auto/dist/run.js:109:5)
##[error]Process completed with exit code 1.
```

If anyone could guide me through the process of using auto for non-js projects, I am happy to add a section to the wiki for *non-js* users like me. :)

My current `release.yml` file looks like this:
```yml
name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn add -D @auto-it/git-tag
          npx auto shipit
```

**Comment by hipstersmoothie** [comment]
Have you seen this doc?

https://intuit.github.io/auto/pages/non-npm.html

**Comment by hipstersmoothie** [comment]
From what you've provided it looks like you tried installing auto through `npm`. It's a bit better to follow this doc

**Comment by hipstersmoothie** [comment]
What type of project are you trying to release?

**Comment by kai-tub** [comment]
> Have you seen this doc?
> https://intuit.github.io/auto/pages/non-npm.html

No.. 🙁
I looked at the [github action page](https://intuit.github.io/auto/pages/build-platforms/github-actions.html) and missed the explanation at the top...

Now everything works as expected.
Sorry for the inconvenience, the issue can be closed. :)
