### ISSUE TITLE
Confusing documentation for hooks

### ISSUE THREAD

**Issue by kai-tub** [intuit/auto#1266]
**Describe the bug**

I am currently trying to use the `exec` plugin in combination with the [`afterAddToChangelog`](https://intuit.github.io/auto/pages/plugins/release-lifecycle-hooks.html#afteraddtochangelog) or the [`beforeCommitChangelog`](https://intuit.github.io/auto/pages/plugins/release-lifecycle-hooks.html#beforecommitchangelog) hook.

I am using auto in a none-npm setting in a GitHub action.
I am confused about the following documentation:
> `currentVersion` - version that was just released
> `lastRelease` - the version before the current version

If my current release is v1.0.4 and I am processing a *patch bump* I would expect from the description to receive `currentVersion` = v1.0.5 and `lastRelease` = v1.0.4
From the variable names alone I don't know what I would expect.

The JSON files I receive for both hooks look like this:

```json
{
    "bump": "patch",
    "commits": [
        {
            ...
        }
    ],
    "releaseNotes": "#### ⚠️ Pushed to `master`\n\n- enstpannent (kainorman.clasen@X)\n\n#### Authors: 1\n\n- Kai Norman Clasen (kainorman.clasen@X)",
    "lastRelease": "v1.0.20",
    "currentVersion": "v1.0.20"
}
2020-05-29T20: 31: 04.6196035Z {
    "bump": "patch",
    "commits": [
        {
            "labels": [],
            "hash": "507ce46a4a33ec8290d36c145373bc8dde0e3b9d",
            "authorName": "Kai Norman Clasen",
            "authorEmail": "kainorman.clasenX",
            "subject": "enstpannent\n",
            "files": [
                "/home/runner/work/github_action_tester/github_action_tester/.autorc",
                "/home/runner/work/github_action_tester/github_action_tester/auto_scripts/echo.sh"
            ],
            "authors": [
                {
                    "email": "kainorman.clasenX",
                    "name": "Kai Norman Clasen",
                    "hash": "507ce46a4a33ec8290d36c145373bc8dde0e3b9d"
                }
            ]
        }
    ],
    "releaseNotes": "#### ⚠️ Pushed to `master`\n\n- enstpannent (kainorman.clasenX)\n\n#### Authors: 1\n\n- Kai Norman Clasen (kainorman.clasenX)",
    "lastRelease": "v1.0.20",
    "currentVersion": "v1.0.20"
}
```

I am not sure if it is a bug or if I misunderstand the documentation.

The `exec` script runs a script and in the script, I would like to access the current and the next (to be published) version, before the tag is published on GitHub.

Thanks!
Kai

**Comment by hipstersmoothie** [comment]
`lastRelease` is the "latest Release" on Github.
`currentVersion` is the current version of the local repo. 

There is a chance for these values to get out of sync that's why they are different. If you notice `bump` has either `patch`, `minor`, or `major`.  In core we apply the bump to the `lastRelease` if it's valid semver, else we fallback to applying the bump to the currentVersion which will always be a valid semver. So if you wanted this version in your plugin you would need to do the semver calculation yourself.

I agree that this is a confusing point of the hooks API. I'm down to add this as another thing changing in #1156. `auto` could probably determine just 1 version to supply to plugins, that already has the bump applied.

**Comment by hipstersmoothie** [comment]
To accomplish that semver bump you could do something like

```sh
npx semver 1.0.0 -i patch
```

But this requires node. You might be able to find a non-node package to do this math

**Comment by kai-tub** [comment]
Ah I see. Thanks for clearing it up!
(Btw that was an amazingly fast answer)

Yes, the version calculation itself is not a big issue. I just assumed that one of these would've had the bump applied and found the documentation unclear.

Thanks again!
