### ISSUE TITLE
auto canary --force bug

### ISSUE THREAD

**Issue by klaygomes** [intuit/auto#1274]
If we configure our project with `onlyPublishWithReleaseLabel` and force a canary we get a lerna error.

The problem is with this function being called with "bump" as empty
https://github.com/intuit/auto/blob/master/plugins/npm/src/index.ts#L715

It happens because of this:
https://github.com/intuit/auto/blob/master/packages/core/src/semver.ts#L69

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.38.2`](https://github.com/intuit/auto/releases/tag/v9.38.2) :rocket:

**Comment by klaygomes** [comment]
thank you!
