### ISSUE TITLE
gradle plugin should not throw an error if a version is not found

### ISSUE THREAD

**Issue by rbellamy** [intuit/auto#1276]
**Describe the bug**

If there is no version property found, the gradle plugin throws an error.

**To Reproduce**

https://github.com/intuit/auto/blob/38a12a819c6594e6687aa21c10b9ff6bddf22ec0/plugins/gradle/src/index.ts#L80

https://github.com/intuit/auto/blob/38a12a819c6594e6687aa21c10b9ff6bddf22ec0/plugins/gradle/__tests__/gradle.test.ts#L41-L46

**Expected behavior**

Like the npm plugin, if it cannot find a version, it should return "0.0.0.0". No error should be thrown.

**Comment by interactwithankush** [comment]
I would like to contribute. Can I please be assigned to this problem?

**Comment by hipstersmoothie** [comment]
Feel free to submit a PR. I don't like assigning them because during hacktoberfest a lot of people call "dibs" but few usually follow through

**Comment by christyjacob4** [comment]
@hipstersmoothie doesn't #1396  already fix this ?

**Comment by ratnamal** [comment]
@hipstersmoothie 
Is this issue fixed?
