### ISSUE TITLE
Docs links do not work

### ISSUE THREAD

**Issue by qoalu** [intuit/auto#1335]
**Describe the bug**

The links on the docs page lead to a 404 page

**To Reproduce**

Open: https://intuit.github.io/auto/docs
Click 'detailed release notes' or 'canaries' link

they lead to a page url like this: https://intuit.github.io/auto/generated/canary.md

**Expected behavior**

A page

**Screenshots**

<img width="501" alt="image" src="https://user-images.githubusercontent.com/1624045/86115177-df8e6500-bacb-11ea-9fcc-0b1a14b2233a.png">

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.40.6`](https://github.com/intuit/auto/releases/tag/v9.40.6) :rocket:
