### ISSUE TITLE
Issue with publish with GitHub Action

### ISSUE THREAD

**Issue by jonniebigodes** [intuit/auto#1366]
**Describe the bug**
I've been working on updating Storybook's Design Systems for Developers tutorial and i've hit a problem with GitHub actions and publishing the package through it.

Each time i try to publish the same problem hits. I've checked the documentation [here](https://intuit.github.io/auto/docs/build-platforms/github-actions) and that was the baseline used for the documentation i've been working on. But each attempt i make i'm getting the following error:

```bash
$ auto shipit
✔  success   Calculated version bump: minor
ℹ  info      New Release Notes

Error: Running command 'git' with args [commit, -m, "Update CHANGELOG.md [skip ci]", --no-verify] failed


*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az20.za1vl5qloybehlk25bnayoxz0g.gx.internal.cloudapp.net>) not allowed


at ChildProcess.<anonymous> (/home/runner/work/design-systems-with-gh-actions/design-systems-with-gh-actions/node_modules/@auto-it/core/dist/utils/exec-promise.js:49:31)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)Error
    at Object.execPromise [as default] (/home/runner/work/design-systems-with-gh-actions/design-systems-with-gh-actions/node_modules/@auto-it/core/dist/utils/exec-promise.js:15:22)
    at Auto.makeChangelog (/home/runner/work/design-systems-with-gh-actions/design-systems-with-gh-actions/node_modules/@auto-it/core/dist/auto.js:1108:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Auto.publishFullRelease (/home/runner/work/design-systems-with-gh-actions/design-systems-with-gh-actions/node_modules/@auto-it/core/dist/auto.js:996:9)
    at async Auto.shipit (/home/runner/work/design-systems-with-gh-actions/design-systems-with-gh-actions/node_modules/@auto-it/core/dist/auto.js:927:27)
    at async run (/home/runner/work/design-systems-with-gh-actions/design-systems-with-gh-actions/node_modules/auto/dist/run.js:70:17)
    at async Object.main [as default] (/home/runner/work/design-systems-with-gh-actions/design-systems-with-gh-actions/node_modules/auto/dist/run.js:110:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I've tried with the default auth token more specifically leaving in `GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`, or by adding a personal access token and use it and each time i run into the same issue. 

**To Reproduce**

- Make a change in my repo.
- Commit. 
- Make a pull request and merge it.
- Wait for the action to process it's workflow.

**Expected behavior**

To be able to publish the package without issues and update the documentation accordingly.

**Screenshots**

**Environment information:**

```bash
Environment Information:

"auto" version: v9.43.1
"git"  version: v2.17.0.windows.1
"node" version: v12.15.0

Project Information:

√ Repository:      jonniebigodes/design-systems-with-gh-actions (​https://github.com/jonniebigodes/design-systems-with-gh-actions​)
√ Author Name:     jonniebigodes
√ Author Email:    my-email-suppressed-for-personal-reasons@mail.com
√ Current Version: v0.1.0
√ Latest Release:  v0.1.0 (​https://github.com/jonniebigodes/design-systems-with-gh-actions/releases/tag/v0.1.0​)

√ Labels configured on GitHub project

GitHub Token Information:

√ Token:            [Token starting with ab23]
√ Repo Permission:  admin
√ User:             jonniebigodes
√ API:              undefined (​undefined​)
√ Enabled Scopes:   repo
√ Rate Limit:       4990/5000
```

**Additional context**

Feel free to provide feedback.

**Comment by hipstersmoothie** [comment]
Could you link me to the build output? And please add `-vv` so we can see the full story.

**Comment by jonniebigodes** [comment]
@hipstersmoothie thank for the reply. Here's the [link to the latest build](https://github.com/jonniebigodes/design-systems-with-gh-actions/runs/859391967?check_suite_focus=true). I'll add the `-vv` shortly.

**Comment by hipstersmoothie** [comment]
Sure!

**Comment by jonniebigodes** [comment]
@hipstersmoothie sorry for the delay. I've updated the script to include `-vv` flag. And per request, [here](https://github.com/jonniebigodes/design-systems-with-gh-actions/runs/861217545) the latest build run. Let me know if you need anything more.

**Comment by hipstersmoothie** [comment]
I think your only problem is you have not author set for commiting.

You can either:

1. Set `author` in your package.json
2. Set name + email in an `.autorc`

**Comment by hipstersmoothie** [comment]
<img width="831" alt="Screen Shot 2020-07-11 at 1 14 12 PM" src="https://user-images.githubusercontent.com/1192452/87233013-6b2fad80-c378-11ea-9909-4d5cb5ada165.png">

**Comment by hipstersmoothie** [comment]
When #1369 releases `auto` will now exit in CI if these values aren't set and provides a helpful error message

**Comment by jonniebigodes** [comment]
@hipstersmoothie thank you for the feedback. I've checked and you're right. The issue was the missing author ( i fumbled fingered that bit 🤦‍♂️)  i've added the author and it's working. 

Going to close this as it's now resolved.

Stay safe
