### ISSUE TITLE
Is there a way to release with "dev-" for push to a dev branch?

### ISSUE THREAD

**Issue by sandip-rai** [intuit/auto#1426]
Hi, is it possible to have separate release tags based on the branch the workflow is running on? Eg, 

- when pushed to master, it would release with tags like v1.2.3

- when pushed to dev branch, it would release with tags like dev-v1.2.3

I have a personal use-case where I deploy with docker and use master for production and dev for active development. Since I tag my docker images with the latest tag in each branch, if I could tag dev branch pushes with the "dev-" tag and tag that to my docker image. Like if I am doing active dev, I would use `docker pull docker_image:dev-v1.2.3` When I am using production-ready docker image,  I would use `docker pull docker_image:v1.2.3`.

I did try the following one but it gave me YAMLSemanticError error with `YAML Error in /home/runner/work/test/test/.autorc:\nMap keys must be unique; "versionBranches" is repeated at line 1, column 1:\n\n{\n^…\n'`
```
{
  "versionBranches": true,
  "versionBranches": "dev-"
}
```

**Comment by hipstersmoothie** [comment]
You can achieve something like that https://intuit.github.io/auto/docs/generated/shipit#release-pipeline

That seem like a prerelease branch https://intuit.github.io/auto/docs/generated/shipit#prereleases

**Comment by sandip-rai** [comment]
@hipstersmoothie Thank you! This solved my use-case.
