### ISSUE TITLE
Lerna w/ Independent versioning can't push due to already existing release

### ISSUE THREAD

**Issue by vincentbriglia** [intuit/auto#1428]
**Describe the bug**

monorepo with independent versioning and master/next/feature branch setup, next branch is default branch, baseBranch (auto) is master. Don't merge or make PR's from next > master, but instead only create feature branch PR's into next. 

first build on next will succeed correctly up until a certain point, where it won't commit versions due to "release already existing", subsequent PR's will fail.
committing on next directly, fixing versions to x.x.x-next.0 will fix the next build. 
feature branches will always succeed with canary releases
pull in PR into next and it will try to publish on the old version.

**To Reproduce**

see repo

**Expected behavior**

commits or pr into next bump including feat and fix should bump the version
commits or pr into next without feat and fix should not fail the build

I have invited you to the private repo @hipstersmoothie where you can see the history

**Comment by hipstersmoothie** [comment]
Will look at this on monday!

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.49.4`](https://github.com/intuit/auto/releases/tag/v9.49.4) :rocket:

**Comment by vincentbriglia** [comment]
@adierkens @hipstersmoothie confirmed working. many thanks!
