### ISSUE TITLE
Strictly validate autorc config before any release

### ISSUE THREAD

**Issue by zephraph** [intuit/auto#143]
**Is your feature request related to a problem? Please describe.**

A few of us at Artsy are working on migrating a lot of repos over to use auto-release. In a batch session, I somehow managed to mess up the config and used `noReleaseLabels` instead of `skipReleaseLabels` on several of the projects. This caused some unnecessary releases. 

**Describe the solution you'd like**

I think the config should be strictly validated. If there are values present that aren't a part of the config (i.e. noReleaseLabels), the release process should fail. Invalid configuration likely means someone is in for a bad time. Similarly if a config object doesn't match an expected type, etc. It seems like there's a start to a json schema that could be used for this purpose ([auto-rc.json](https://github.com/intuit/auto-release/blob/master/src/auto-rc.json)). 

**Describe alternatives you've considered**

If you want to take a lighter approach I'd recommend at the very least having a `validate` command that checks the validity of the configuration.

**Comment by orta** [comment]
Jest has a JSON config validator - https://github.com/facebook/jest/tree/master/packages/jest-validate#jest-validate

**Comment by zephraph** [comment]
I'm working through creating a schema via [quicktype](https://www.npmjs.com/package/quicktype). 

https://app.quicktype.io?share=vgnvzBMgaixe5c9qUCD2.

It actually also generates code to automatically validate it... https://app.quicktype.io?share=yxg2tubeMvnazWyklgkz. We could use something like that?

**Comment by orta** [comment]
Probably shouldn't build something if it requires a human accessing an external website IMO, in Danger [I generate](https://github.com/danger/danger-js/blob/master/package.json#L60) JSON [schemas](https://github.com/danger/danger-js/blob/master/source/danger-incoming-process-schema.json) from TypeScript types via a node module and automate them on deploys, then it'll never get out of sync

**Comment by hipstersmoothie** [comment]
I like that

**Comment by zephraph** [comment]
quicktype is an npm package, it just has a web interface too. I agree, it should be automated.

**Comment by hipstersmoothie** [comment]
can it take a TS interface and create a JSON schema? that would be awesome

**Comment by hipstersmoothie** [comment]
https://github.com/lbovet/typson
https://github.com/YousefED/typescript-json-schema
https://github.com/vega/ts-json-schema-generator

**Comment by hipstersmoothie** [comment]
looks like your quicktype links do what i'm describing. that's so cool! Making this part of our release process would be pretty cool.

Maybe we could even make a plugin to do publishing as a VSCode extension

**Comment by zephraph** [comment]
I'm all about both of those things. I can work on this, but it'll have to wait until the weekend. I'm gonna take it easy tonight, ha. I'll see if I can set up the typescript interface to json-schema process. Don't think it'll be too hard. Hardest part is really just figuring out what should go in the schema.

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.15.0` :rocket:
