### ISSUE TITLE
jira plugin not found (Yarn v2)

### ISSUE THREAD

**Issue by myndelx** [intuit/auto#1441]
**Describe the bug**

When I install the jira plugin with Yarn v2 and add it to .autorc, `auto` trigger a warning saying it could not find the plugin:

```
> yarn run auto info --list-plugins
⚠  warning   Could not find plugin: jira
(node:1270067) [MODULE_NOT_FOUND] Error: @auto-it/core tried to access @auto-it/jira, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

⚠  warning   Could not find plugin: jira
Found the following plugins in your .autorc:

- npm (@auto-it/npm)
- released (@auto-it/released)
- jira ()
```

When I use an other plugin, like `slack` for example, it's working properly.

**To Reproduce**

Install the latest Yarn Berry
Install the `@auto-it/jira` plugin

**Expected behavior**

The plugin should be working properly.

**Environment information:**

```txt
> yarn run auto info
⚠  warning   Could not find plugin: jira
(node:1271759) [MODULE_NOT_FOUND] Error: @auto-it/core tried to access @auto-it/jira, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Environment Information:

"auto" version: v9.49.4
"git"  version: v2.25.1
"node" version: v10.21.0
"GHE" version: v2.21.1
```

**Additional context**

```txt
> yarn -v
2.1.1
```

**Comment by hipstersmoothie** [comment]
I think this should be fixed in [`v9.49.5`](https://github.com/intuit/auto/releases/tag/v9.49.5)

**Comment by myndelx** [comment]
Will test that on next monday, thanks @hipstersmoothie!

**Comment by myndelx** [comment]
I've tested the `v9.49.5` version and it works like a charm! Thanks @hipstersmoothie!
