### ISSUE TITLE
Publish Auto with --exact

### ISSUE THREAD

**Issue by 10hendersonm** [intuit/auto#1448]
**Describe the bug**

`auto` declares internal dependencies with careted versions (ex: `auto@9.47.1` calls `@auto-it/npm@^9.47.1`).

**To Reproduce**

```
npm install auto@9.47.1

npm ls auto            
# /Users/me/development/projects/tmp
# └── auto@9.47.1 

npm ls @auto-it/npm               
# /Users/me/development/projects/tmp
# └─┬ auto@9.47.1
#   └── @auto-it/npm@9.50.0 
```

**Expected behavior**

I'd like it to install with exact versioning so `9.47.1` of core gets `9.47.1` of all dependent packages, thus preventing introduction of an unintentional breaking change as versions of packages minorly drift.

```
npm install auto@9.47.1
npm ls @auto-it/npm               
# /Users/me/development/projects/tmp
# └─┬ auto@9.47.1
#   └── @auto-it/npm@9.47.1 
```

**Screenshots**

**Environment information:**

We're calling our own CLI which calls auto, so there's some layers of abstraction I'd have to peel back to provide this and I'm unsure it's relevant to the issue at hand. If desired, I can produce one.

```txt
```

**Additional context**

My team's publish pipeline broke when [the `--registry` argument was added to `lerna publish`](https://github.com/intuit/auto/blob/master/plugins/npm/src/index.ts#L872). That error is another discussion (somehow a trailing slash on the `--registry` prevents publishing all packages?) which I'll create in another place (created #1449).

I hadn't expected to be able to take breaking changes as we were still running `auto@9.47.1` at the time, but the change which broke us was introduced in `@auto-it/npm@9.48.3`. Given the auto monorepo doesn't publish using `--exact` versioning, we were auto-upgraded into the higher version of the `npm` plugin.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.50.1`](https://github.com/intuit/auto/releases/tag/v9.50.1) :rocket:
