### ISSUE TITLE
auto init with customizing the default labels sets empty objects

### ISSUE THREAD

**Issue by mattfelten** [intuit/auto#1461]
**Describe the bug**

I'm testing `auto` on a project that already has GitHub labels set up using `lerna-changelog` and not interested in changing them at the moment so wanted to rename some of the defaults to match the naming we're already using. I went through the interactive tool and when it finished, my labels array in `package.json` doesn't have any of my changes.

I've tried it twice.

```
"auto": {
    "plugins": [
      "npm",
      "all-contributors",
      "first-time-contributor"
    ],
    "onlyPublishWithReleaseLabel": true,
    "labels": [
      {
        "overwrite": true
      },
      {
        "overwrite": true
      },
      {
        "overwrite": true
      },
      {
        "overwrite": true
      },
      {
        "overwrite": true
      },
      {
        "overwrite": true
      },
      {
        "overwrite": true
      },
      {
        "overwrite": true
      },
      {
        "overwrite": true
      },
      {
        "overwrite": true
      }
    ]
  }
```

**To Reproduce**

Run `npx auto init`, set whatever options. When asked `Would you like to use customize the default labels?`, hit y. Customize names and descriptions of some labels. Finish successfully. See `package.json` not have info set.

**Expected behavior**

I expected the label objects to have the values I put into the CLI editor

**Environment information:**

```txt
$ npx auto info
⚠  warning   Could not find plugin: all-contributors
⚠  warning   Could not find plugin: first-time-contributor
✖  error     Found configuration errors:

"labels.0.name"

Expected "string" but got: undefined

"labels.1.name"

Expected "string" but got: undefined

"labels.2.name"

Expected "string" but got: undefined

"labels.3.name"

Expected "string" but got: undefined

"labels.4.name"

Expected "string" but got: undefined

"labels.5.name"

Expected "string" but got: undefined

"labels.6.name"

Expected "string" but got: undefined

"labels.7.name"

Expected "string" but got: undefined

"labels.8.name"

Expected "string" but got: undefined

"labels.9.name"

Expected "string" but got: undefined
 

⚠  warning   These errors are for the fully loaded configuration (this is why some paths might seem off).
```

**Additional context**

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.50.9`](https://github.com/intuit/auto/releases/tag/v9.50.9) :rocket:
