### ISSUE TITLE
Ability to omit the 'Pushed to <branch>' section from the changelogs

### ISSUE THREAD

**Issue by mshick** [intuit/auto#1471]
**Is your feature request related to a problem? Please describe.**

While I do appreciate the subtle shaming, I'd like to make my release notes good for customers, who might find that section confusing or off-putting.

**Describe the solution you'd like**

The ability to omit that section from the release notes via a label config option.

**Describe alternatives you've considered**

The `omit-commit` and `omit-release` plugins, but they don't seem to have the appropriate context to exclude these commits.

**Comment by hipstersmoothie** [comment]
You should be able to override the label with less shame 😜

**Comment by mshick** [comment]
Ah, shoot, yes this worked in my `.autorc`

```json
    {
      "name": "pushToBaseBranch",
      "changelogTitle": "",
      "releaseType": "none",
      "overwrite": true
    }
```

Thanks again!
