### ISSUE TITLE
Custom commit message by release context

### ISSUE THREAD

**Issue by mattfelten** [intuit/auto#1508]
**Is your feature request related to a problem? Please describe.**

I'm looking to change the commit message for version bumps only for `latest` releases so that I can add something to trigger a CI job to publish a website. I don't want this to happen for prerelease or canary releases, only latest.

I know `auto shipit` has a `--message` option but at time of running the command, I don't know what type of release is being made.

**Describe the solution you'd like**

Not sure. I could see having some sort of message template options in `.autorc` but no idea how that'd work.

**Describe alternatives you've considered**

I imagine there might be a way to do this with a custom plugin using the `version` lifecycle hook but I'm not sure I see a way of seeing the release context here like you can with `afterShipIt`

**Comment by hipstersmoothie** [comment]
So we could def add commit message options. The current --message flag is for the changelog commit so that wouldn't quite work. 

Could you kick off the job in another way? If you could kick it off by yum a cli command there are a few ways to accomplish that

**Comment by mattfelten** [comment]
There might be. I need to investigate that more. If there is, is the `afterShipIt` hook the best place to do this where I can check for only `latest` releases?

**Comment by hipstersmoothie** [comment]
Yup a plugin like that would look like

```js
const { execSync } = require("child_process");

module.exports = class KickOffCIPlugin {
  /**
   * Setup the plugin
   *
   * @param {import('@auto-it/core').default} auto
   */
  apply(auto) {
    auto.hooks.afterShipIt.tapPromise(
      "kick off CI",
      async (_, __, { context }) => {
        if (context === "latest") {
          execSync("do your thing");
        }
      }
    );
  }
};
```

**Comment by hipstersmoothie** [comment]
@mattfelten does this suffice?

**Comment by mattfelten** [comment]
It looks like it's working. I'm gonna be testing and tweaking it more but I really appreciate your help on this!
