### ISSUE TITLE
all-contributors: Fails if using a file other than README

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#1552]
Currently the all-contributors plugin will always update the README even if the rc says to update another file. Fix this!

**Comment by evanhsu** [comment]
I'm able to specify a file other than `README.md` as long as I run `npx all-contributors init` to initialize the target file.

Tested with `auto@9.53.1` and `"@auto-it/all-contributors": "^9.53.1"`
![image](https://user-images.githubusercontent.com/189640/94655897-885f8280-02bc-11eb-8882-d550a73f0685.png)

**Steps to repro:**
1. Run `npx all-contributors init`
1. Specify when prompted that contributors should be listed in the `CONTRIBUTORS.md` file:
    
    ![image](https://user-images.githubusercontent.com/189640/94654999-1f2b3f80-02bb-11eb-884d-8efe3556fadb.png)

1. Make an update that satisfies the contribution criteria (open a PR with a changed file in one of the "watched" paths).

1. Observe that the `CONTRIBUTORS.md` file now has the following contents:

```markdown

<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->
<table>
  <tr>
    <td align="center"><a href="https://github.com/evanhsu"><img src="https://avatars2.githubusercontent.com/u/189640?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Evan Hsu</b></sub></a><br /><a href="https://github.com/evanhsu/evanhsu/versionme/commits?author=evanhsu" title="Code">💻</a> <a href="https://github.com/evanhsu/evanhsu/versionme/commits?author=evanhsu" title="Documentation">📖</a></td>
  </tr>
</table>

<!-- markdownlint-restore -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->

```

**However**, if I just try to update the `.all-contributorsrc` file now to point at a different file (_without_ re-running `npx all-contributors init` on the new file) then I don't see any updates to the contributors list for subsequent PRs.

---
Can you confirm that the issue still exists and possibly provide steps to reproduce?  I'm hoping it's still broken so I can nab some Hacktoberfest shwag 🤣

**Comment by hipstersmoothie** [comment]
Sorry for the false alarm @evanhsu. Thanks for the detailed breakdown
