### ISSUE TITLE
cocoapod: Pass verbose flag to pod commands when auto is ran with -v

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#1553]

**Comment by dcortright** [comment]
Hi @hipstersmoothie, I would like to work on this issue!

**Comment by hipstersmoothie** [comment]
Go for it!

**Comment by dcortright** [comment]
Great. Thank you!

**Comment by dcortright** [comment]
@hipstersmoothie Created the PR: https://github.com/intuit/auto/pull/1580 for this issue.
