### ISSUE TITLE
Auto Blog page 404 error

### ISSUE THREAD

**Issue by christyjacob4** [intuit/auto#1560]
Clicking on any of the blog links [here](https://intuit.github.io/auto/blog) takes the user to a 404 page

**To Reproduce**
1. Visit https://intuit.github.io/auto/blog
2. Click on any of the blog posts.

**Expected behaviour**
The correct blog page must load

**Screenshots**
![Screenshot 2020-10-04 at 2 16 25 PM](https://user-images.githubusercontent.com/20852629/95011137-31570600-064c-11eb-8cb9-01faf0fdef58.png)

**Environment information:**
Not relevant

**Additional context**

Here's what I found , when clicking the blog posts, the user is taken to https://intuit.github.io/auto/auto/blog/both-worlds and hence causes a 404 error. Ideally he should be taken to https://intuit.github.io/auto/blog/both-worlds and manually deleting `auto/` from the URL takes us to the correct page. 

While running the docs locally by running `yarn docs:generate && ignite dev` and visiting `localhost` we do not face this issue and the blogs load correctly. 

But while running `yarn docs:generate && ignite build` and examining the `docs/out/blog.html` file , the href attributes are incorrectly set 

```html
<a class="rounded border border-gray-300 py-8 px-10 flex items-center dark:bg-gray-900"
            href="/auto/auto/blog/both-worlds"/>

<a class="rounded border border-gray-300 py-8 px-10 flex items-center dark:bg-gray-900"
            href="/auto/auto/blog/npm-canary-scope"/>
```

I'm unsure if this is an issue with `ignite build` or a folder structure issue in the repo. I would love some more insights and would like to fix it.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.5.0`](https://github.com/intuit/auto/releases/tag/v10.5.0) :rocket:
