### ISSUE TITLE
Version prefix is not being added in Pre-releases

### ISSUE THREAD

**Issue by brunobertoldi** [intuit/auto#1567]
**Describe the bug**

The prefix `v` is not being added when `auto shipit` (or `auto next`) is executed in a prerelease branch.
The option `--no-version-prefix` is ignored.

**To Reproduce**

1. Run `auto shipit` without `--no-version-prefix` in a branch listed in `prereleaseBranches`
1. The published Github Pre-Release doesn't contain the prefix `v`

**Expected behavior**

Add prefix `v` to prerelease branches when `--no-version-prefix` is false.

**Screenshots**

```jsonc
// .autorc.json
{
  "baseBranch": "master",
  "prereleaseBranches": ["develop"]
}
```

Note that the Release contains the prefix.

![image](https://user-images.githubusercontent.com/19298197/95251381-d65f1380-07f1-11eb-81b9-26b95857c15d.png)

**Environment information:**

```txt
"auto" version: v9.54.3
"git"  version: v2.28.0
"node" version: v12.18.4
```

**Additional context**

I've noticed that the `next` command is not using the `prefixRelease` function as other commands do.
I can implement the parameter `--no-version-prefix` for the `next` command if that makes sense, or just use `prefixRelease` directly without the new parameter.

**Comment by hipstersmoothie** [comment]
is this with the npm plugin?

**Comment by brunobertoldi** [comment]
No, without the npm plugin

**Comment by hipstersmoothie** [comment]
Any chance this repo is public?

**Comment by brunobertoldi** [comment]
Yes! I created a minimum working example here:
https://github.com/brunobertoldi/auto-test/releases

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.54.4`](https://github.com/intuit/auto/releases/tag/v9.54.4) :rocket:

**Comment by hipstersmoothie** [comment]
@brunobertoldi Can you test out with that version?

**Comment by brunobertoldi** [comment]
Yes, it works!
https://github.com/brunobertoldi/auto-test/releases

Thanks, @hipstersmoothie!

**Comment by brunobertoldi** [comment]
Oh, I've noticed that the fix doesn't cover the `--quiet` flag:
https://github.com/brunobertoldi/auto-test/runs/1220329534?check_suite_focus=true

<details>
<summary>Github Action Screenshot</summary>

![image](https://user-images.githubusercontent.com/19298197/95330124-75c9e800-087e-11eb-81cc-58454b3c6955.png)

</details>

Should I open another issue?
