### ISSUE TITLE
Can the changelog be committed to a different repo? 

### ISSUE THREAD

**Issue by Kimba666** [intuit/auto#1579]
**Is your feature request related to a problem? Please describe.**
Lets say you are in the base directory for Repo A, 
And you run the command 'yarn auto latest',
Is there a way to have the action do everything that it would normally do (bump version based on tags, apply new tag) BUT commit the Changelog.md file to Repo B instead of Repo A?

I am trying to make a library of changelogs in one Repository that will contain the Changelog.md files for multiple other repositories.
**Describe the solution you'd like**
I'd like to know if there is a way to specify which repo the commend will commit the changelog.md file to, and if it can be changed. 

I have a github action workflow file that triggers the 'yarn auto latest' command whenever a pull request's review status=approved. This keeps and automatically updated changelog and version control. My team has branch protection for some of our repos which causes the commands to fail due to not allowing direct commits to the dev or master branches. 
I want to know how I can have the command do everything it would normally do, but commit the changelog.md file to a specific branch of a different repository.
**Describe alternatives you've considered**

**Additional context**

**Comment by hipstersmoothie** [comment]
This doesn't sound like something I would include in this repo. but it does seem like a good idea for a plugin.

The plugin would use the `afterAddToChangelog` hook, read the new changelog, and then use octokit to make a PR/or push to the other repo

**Comment by JWolfLive** [comment]
Thank you my friend I'll do some research and testing. :)

**Comment by hipstersmoothie** [comment]
As this isn't something I plan to integrate I'm going to close this issue. Feel free to open again if further discussion is needed
