### ISSUE TITLE
Use SSH keys for Git authentication

### ISSUE THREAD

**Issue by tinytim84** [intuit/auto#1587]
**Is your feature request related to a problem? Please describe.**

We are currently trying to move our release workflow from semantic-release to Auto.  We use protected branches and are having authentication issues in the git push back to our branch.  We prefer not to use personal access tokens because they're tied to specific users and they have access to the whole organisation rather than being scoped to a specific repo.  With semantic-release we are able to authenticate using SSH keys, but that doesn't seem to be possible with Auto.

**Describe the solution you'd like**

We would like to be able to authenticate with SSH keys instead of personal access tokens.

**Describe alternatives you've considered**

Tried using the `ssh-key` attribute on [Checkout V2](https://github.com/actions/checkout#usage), but this still didn't allow it to push back.

**Comment by hipstersmoothie** [comment]
I've never used ssh w/GitHub myself and would def accept a PR to improve this part of auto. I might be able to take a look at this later this week or next week.

**Comment by hipstersmoothie** [comment]
It's in [this function](https://github.com/intuit/auto/blob/master/packages/core/src/auto.ts#L589). Code is somewhat similar to what you would find in semantic release

**Comment by tinytim84** [comment]
@hipstersmoothie I've created a PR for this: https://github.com/intuit/auto/pull/1590

**Comment by tinytim84** [comment]
Thanks for approving!  How can I use this canary version in place of the production version that I'm currently using?

**Comment by hipstersmoothie** [comment]
Are you deploying a javscript based project?

**Comment by hipstersmoothie** [comment]
Sweet! should be easy to test it out. Our canary versions are published under a different scope. Change all plugins from `@auto-it` to `@auto-canary` and the main `auto` package to `@auto-canary/auto` and set all the versions to `9.59.1-canary.1590.19456.0`

**Comment by tinytim84** [comment]
Thanks, I've got the canary version in now.  I'm going to do some testing, think there might need to be a little more done on this one before it's ready.

**Comment by tinytim84** [comment]
I'm just having a little trouble verifying whether this has been successful or not.  To test the value of `auto.remote` I created a simple plugin that hooks into `beforeShipIt` and it just console logs `auto.remote`.  Then I just do a dry-run on `auto shipit` to see what the remote url displays as.  I've created a personal access token with no access rights in the hope that it would cause [verifyAuth](https://github.com/tinytim84/auto/blob/e8e407fbd32032617f7617ee7abc6ea46941eeea/packages/core/src/auto.ts#L622) to fail, thereby moving on to eventually use the `ssh_url`.  However that doesn't seem to be happening.  `auto.remote` is returning as `https://***my_pat***@github.com/xeroxinteractive/config`.  I thought it needed a token with write access if the branch was protected?  I'm just not sure why verifyAuth appears to be passing.

**Comment by AndrewLeedham** [comment]
I wonder if a dry run push will fail with an invalid or no token, but because it is not actually pushing anything it does not care about push permissions specifically. What if we do an octokit get for this data: https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-a-repository and check if `permissions.write` is true?

**Comment by tinytim84** [comment]
@hipstersmoothie I've updated my PR to include a check on whether push permissions available before doing the `verifyAuth` check. This should cause it to fail if the token provided doesn't have push permissions, so it will then continue on to check the other methods.

**Comment by tinytim84** [comment]
@hipstersmoothie I've made another change to this, would you be able to create a canary version that I can test please?
