### ISSUE TITLE
Released Plugin: Error on shipit

### ISSUE THREAD

**Issue by benskz** [intuit/auto#1602]
**Describe the bug**

When running `auto shipit`, sometimes, the released plugin errors (See screenshot below). I'm currently unsure how to reproduce this reliably.

**Expected behavior**

Released plugin should comment on relevant PRs and not throw an error.

**Screenshots**

![image](https://user-images.githubusercontent.com/16744051/97015350-64056780-1543-11eb-98ba-922448b4b8be.png)

**Additional context**

The comment and label were still added to the PR in question, it seems it errored after the fact.
Error seemingly caused by a `null` `pr.data.body`

**Comment by benskz** [comment]
Further testing seems to suggest that if the PR body is not empty this error never occurs.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.60.1`](https://github.com/intuit/auto/releases/tag/v9.60.1) :rocket:
