### ISSUE TITLE
monorepo, independent packages, next branch and main branch: versioning mismatch over time

### ISSUE THREAD

**Issue by vincentbriglia** [intuit/auto#1628]
**Is your feature request related to a problem? Please describe.**
when doing somewhat long development cycles into a next branch, publishing packages to the github package registry, using lerna and lerna workspaces through yarn, we end up with mismatched versions. 

**Describe the solution you'd like**

because versions aren't updated in the package.json of each package, and we can't use 'file:/../packages/x-something' because of lerna and lerna workspaces, I think i'd like to investigate the feasibility of also updating the `package.json` for each package in the next branch with the new correct built version of the dependent packages. currently this only happens in non-prerelease branches. 

**Describe alternatives you've considered**

manually updating versions, marking dependencies more openly in the semver context (using ^ and ~) 

**Additional context**

we've tried to open up react, react-dom, @types/react and @types/react-dom with less restrictive versioning, we didn't have the problem before, because we were being very strict to begin with. now we are seeing an issue where some of the packages we've published in the next branch still have a dependency on the package.json version from the next branch which has never been updated through auto. https://github.com/LEGO/klik/pull/368

**Comment by vincentbriglia** [comment]
This has worked with yarn, because yarn de-duped this problem away for us. but some teams are using npm and npm is a bit more strict. what this means is that the dependency tree is not updated correctly. 

in the next branch `@lego/klik-react@1.0.0-next.33` which should have a dependency on `@lego/klik@1.0.0-next.16` still has a dependency on `@lego/klik@0.0.2-next.0` because that's what specified in `@lego/klik-react` package.json when published to the registry.

imho this is wrong.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.2.0`](https://github.com/intuit/auto/releases/tag/v10.2.0) :rocket:

**Comment by vincentbriglia** [comment]
@hipstersmoothie the inner references were not updated, you can take a look here: https://github.com/LEGO/klik/commit/329d3b165b87f01486b9b550ee9766e9025a64f2

**Comment by hipstersmoothie** [comment]
Digging deeper on this now. I think this is a lerna issue? just playing around with lerna it seems that it's not updating these "inter dependencies" during a publish.

**Comment by hipstersmoothie** [comment]
I think i've found the issue

**Comment by hipstersmoothie** [comment]
I think this next version should actually fix it

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.2.1`](https://github.com/intuit/auto/releases/tag/v10.2.1) :rocket:

**Comment by vincentbriglia** [comment]
it did not fix: https://github.com/LEGO/klik/commit/15620c16cff397f237dc86e7b648a5cdea067dbf one is a dependency of the other, also strange that it bumped to 1.0.1 instead of sticking to 1.0.0
