### ISSUE TITLE
Option for released plugin to ignore certain PRs

### ISSUE THREAD

**Issue by tinytim84** [intuit/auto#1634]
**Is your feature request related to a problem? Please describe.**

We use dependabot for automated dependency updates.  Now we're switching to use auto for our releases, we get a lot of notification spam due to comments that are left in each PR that dependabot has opened.

**Describe the solution you'd like**

We'd like to be able to specify a label that when present, the released plugin would ignore these PRs and not leave comments.

**Additional context**

I think I've found the relevant section of the released plugin that would need updating and I'm happy to give it a go if you'd be open to accepting this kind of change?  I would need a pointer on where you'd want me to put the config setting where you could specify the label to be ignored.

**Comment by hipstersmoothie** [comment]
I'm down for this. I don't think this should require any config though. We already have this package [@auto-it/botlist](https://github.com/intuit/auto/blob/master/packages/bot-list/src/index.ts) that `auto` uses to ignore bots in other places. It could be used here to filter out PRs made by bots too.

We could then add a config option that lets the `release` plugin comment on those PRs. I'll probably get this out today 😄

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.3.0`](https://github.com/intuit/auto/releases/tag/v10.3.0) :rocket:

**Comment by tinytim84** [comment]
Great!  And thanks for the quick response @hipstersmoothie!
