### ISSUE TITLE
afterShipIt hook doesn't have dry run info

### ISSUE THREAD

**Issue by mattfelten** [intuit/auto#1649]
Digging into #1508 more, I'm realizing that the `afterShipIt` hook doesn't have a way to see if it was run in a dry run or not. So our dry runs are kicking off CI builds. The `beforeShipIt`'s `context` includes info on whether it was run in a dry run or not, but `afterShipIt` doesn't. Could we include `dryRun` info to the `afterShipIt` hook?

**Comment by hipstersmoothie** [comment]
Good catch. Def open to adding this. Wanna make a PR?

**Comment by mattfelten** [comment]
At a glance this is over my head, but I'll take another look when I have some time.

**Comment by hipstersmoothie** [comment]
i have time. I'll do it now :D

**Comment by mattfelten** [comment]
Thank you!
