### ISSUE TITLE
Canaries for git-tag plugin

### ISSUE THREAD

**Issue by msonnleitner** [intuit/auto#1678]
**Is your feature request related to a problem? Please describe.**

When using auto with npm (for private packages) or gittag plugin it seems they are not supported.

Basically, the idea would be to use the gittags for [skaffold](https://skaffold.dev/) to create [tags](https://skaffold.dev/docs/pipeline-stages/taggers/). 
>If the workspace is on a Git tag, that tag is used to tag images

**Describe the solution you'd like**

If using a git-tag with a PR branch and running, a tag like 1.2.3-canary.123.0 is created, which could then be used by skaffold to create the image with that version. (Publishing that to Github would probably not be necessary in that case, but I am not sure if this makes sense)

**Describe alternatives you've considered**

**Additional context**
The application is built with npm, but not published to npm, but deployed to kubernetes.

I am not entirely sure if this makes sense after reading https://github.com/lerna/lerna/issues/2206

**Comment by hipstersmoothie** [comment]
I'm not all that familiar with skaffold but it seems like that is your "publishing platform". It may make more sense to create a plugin that is generally applicable to `skaffold` projects or a custom plugin to fit your project.

> Publishing that to Github would probably not be necessary in that case, but I am not sure if this makes sense

`auto` is usually run from a CI, so not pushing the tag would mean it's lost most of the time. I think tagging canaries could lead to a lot fo noise in the repo too

**Comment by msonnleitner** [comment]
Well the idea was to create git tags which can also be pushed to the git repo. However, a Github release does not make much sense. Then again, you're right it probably adds quite some noise to the repo... well maybe it then does not make so much sense after all
