### ISSUE TITLE
Commits for version bump is from global git config

### ISSUE THREAD

**Issue by sethomas** [intuit/auto#1718]
**Describe the bug**

Looking at [this](https://github.com/intuit/auto/blob/master/packages/core/src/auto.ts#L1922-L1927), the version bump commit is from global git config user instead of `GH_TOKEN` user or `auto.author` defined [here](https://intuit.github.io/auto/docs/configuration/autorc#author).

My use case is when running an `auto shipit` command on a computer used for other dev activities instead of a dedicated CI environment.

**To Reproduce**
1. have git installed on your machine, set the global `name` and `email` to be your user via `git config set`
1. make a bot user account, add bot user to the repo, generate a token from github
1. setup a repo to use `auto`, set `GH_TOKEN` in your `.env` to be from the bot user
1. on your machine, run an `auto` release command: `auto shipit`

If I look at `releases` on the guthub repo, the release is from the bot account. Great! But if I view the commits, the version bump commit is coming from my global `git config user.name`.

**Expected behavior**

Both `releases` and git commit history for version bump would be from the user account defined in `GH_TOKEN`.

**Additional context**

I do have `auto.author` in `package.json` as a different value than my global git config which I am unsure what it does now?

**Comment by hipstersmoothie** [comment]
Currently we only do not set git's `user.email` and `user.name` if they are already set on the machine. This goes all the way back to #124. We could try to set it then restore it after auto is done, but i hesitate to do this. If something were to go wrong during an `auto` run and we weren't able to reset the git author it would leave your local machine in a bad state.

**Comment by sethomas** [comment]
@hipstersmoothie ah I am not implying that `auto` should set `user.email` or `user.name`, I just want it to respect the [`auto.author`](https://intuit.github.io/auto/docs/configuration/autorc#author) (or the `GH_TOKEN` name/email) instead of using the global `user.email` and `user.name` from the machine doing the release.

What is the use currently of `auto.author`?

**Comment by hipstersmoothie** [comment]
Totally understand that, it's just to achieve that we either need to call `git config` or pass a flag to all `git` commands that need `name` and `email` set.

> What is the use currently of auto.author when global git user is defined?

When on a machine where `email` and `name` are already set it effectively does nothing.

https://github.com/intuit/auto/blob/master/packages/core/src/auto.ts#L1922-L1927

**Comment by sethomas** [comment]
@hipstersmoothie really appreciate the replies.

Can you explain why the there is a difference between the user associated with the "releases" in github vs the user tied to the commit?

**Comment by hipstersmoothie** [comment]
There isn't a good one 😅  This conversation made me realize that we don't really even need any of those configuration options and can get that information from the GH_TOKEN.

[This change is planned for whenever v11 happens](https://github.com/intuit/auto/issues/1721)

[And i've already made some changes to use the tokens name and email](https://github.com/intuit/auto/pull/1720)

**Comment by sethomas** [comment]
@hipstersmoothie Splendid! I shall subscribe to both links you shared. I'll leave closing this specific issue up to you. Thank you!
