### ISSUE TITLE
Question about merging a PR in a pre-release branch

### ISSUE THREAD

**Issue by myndelx** [intuit/auto#1737]
When merging a PR with a label that has a `releaseType: none` (e.g. `internal`) in a pre-release branch (e.g. `next`), the `yarn auto shipit` command will still trigger a new pre-release (e.g. `mypkg-1.0.0-next.1`) whereas if I do the same on the `master` branch, no new release will be triggered, because of the `releaseType: none`. Is it the normal behavior? Why this difference?

**Comment by hipstersmoothie** [comment]
This is a great callout! They `none` labels should behave the same on a prerelease branch.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.12.1`](https://github.com/intuit/auto/releases/tag/v10.12.1) :rocket:

**Comment by myndelx** [comment]
Thanks you so much @hipstersmoothie for your reactivity! :muscle:
