### ISSUE TITLE
Patching old major releases

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#175]
**Is your feature request related to a problem? Please describe.**

"Something I've been thinking about (and I'm not sure if this is ever a thing we'd support) is the potential for releases that aren't master (or the main branch). Up until this point, we've always assumed that there's 1 path for releases to take -- and they're always linear (using the latest version on npm or github).

What happens in the case of needing to patch a previous release? (1.x has a bug, master is on 2.x but you want to patch 1.x w/ a fix too) If we're going off of the lerna or pkg version I think we'd be okay. The PR lookups would calc a new semver bump and apply that to the version in the current branch.

If we change this to use something outside of the git tree I don't think we'd be able to support that behavior, as there's only ever 1 latest on npm (or wherever we fetch the latest version from)"

~ @adierkens 

version:
- We calculate `version` using the latest release - could this easily switch to the package version?
- The latest release on github might be a problem. I don't think you can actually programmatically set the "Latest Release". So when publishing a patch to 1.x it would become the latest release. 

release/changelog
- `getCurrentVersion` returns lastRelease if gt(lastRelease, lastVersion) - so this would need to be aware of that too 

**Describe the solution you'd like**

We need to depend on latestRelease to be sure that it has a git tag associated with it, so switching isn't an option because we can't be sure that the latest npm version has a tag (like in the thing this issue describes).

I think that we would probably need a new flag that versions from the last git tag. `--from-git`

With that the release command would probably work. We would have to sort out what the changelog looks like.

the `--from-git` flag could also override looking at NPM for anything.

**Comment by adierkens** [comment]
:rocket: Issue was released in v8.6.0 :rocket:
