### ISSUE TITLE
Add 'target' option to canary command

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#1753]
**Is your feature request related to a problem? Please describe.**

Sometimes when editing a PR body the canary version will erase my work. 

**Describe the solution you'd like**

There should be a `target` option that can be set to `pr-body`, `message`, or `status`.

- `pr-body`: Add to the pull request body. default, what exists today
- `message`: Post as a message to the PR
- `status`: Post as a status on the PR

**Describe alternatives you've considered**

Cry myself to sleep dreaming of all the quality PR bodies I had lost

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.21.0`](https://github.com/intuit/auto/releases/tag/v10.21.0) :rocket:
