### ISSUE TITLE
Website search links failing

### ISSUE THREAD

**Issue by AndrewLeedham** [intuit/auto#1754]
**Describe the bug**

Links in the search bar at the top of https://intuit.github.io/ seem to be pointing to `/auto/auto/etc/`, when selecting them with the enter key, instead of `/auto/etc` which is causing them to 404. Clicking them still works, it only seems to occur with keyboard navigation.

**To Reproduce**

Search for labels, hit enter, get a 404 page.

**Expected behavior**

Links not to 404 on enter.

**Screenshots**

https://user-images.githubusercontent.com/5557458/105975704-2b67b380-6087-11eb-88bd-f65466c4efd2.mp4

**Environment information:**

```txt
Chrome 88.0.4324.96
macOS Big Sur 11.1
```

**Comment by hipstersmoothie** [comment]
Fixed! thanks for the heads up!
