### ISSUE TITLE
Plugin Ideas

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#176]
Potential plugins for `auto`

- ~java~ #414 
- ~post to Twitter~ #422 
- ~rust~ #587 
- go
- ruby
- python (pip)
- ~GitHub pages~ #1031 
- VSCode plugin
- salesforce appexchange (https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_package.htm#cli_reference_force_package)

Feel free to suggest some!

**Comment by aleclarson** [comment]
Here's a plugin I need right away: It scans the commit messages of a PR for `semantic-release` style prefixes (eg: `fix:`, `feat:`, `BREAKING`) and automatically applies the appropriate `patch`/`minor`/`major` label to the PR. [Source](https://twitter.com/alecdotbiz/status/1086721784429363201)

**Comment by hipstersmoothie** [comment]
Yeah that sounds like a good plugin! I'm okay with it being official. All though we might need to add an extra hook or two for this behavior

**Comment by hipstersmoothie** [comment]
A hook with the name `parseCommit` could enable this here 

https://github.com/intuit/auto-release/blob/5220097f4ce075f4097d62492cd08b6e9551fca2/src/log-parse.ts#L141

**Comment by aleclarson** [comment]
We could use [parse-commit-message](https://www.npmjs.com/package/parse-commit-message) to extract metadata from commits (though its dependency on [esm](https://www.npmjs.com/package/esm) makes it [a little heavy](https://packagephobia.now.sh/result?p=parse-commit-message), but that will be removed once NodeJS supports ES modules natively). In the meantime, we could fork it and remove the `esm` dependency if it bothers us enough. Even if we don't fork, it's still [~6x smaller](https://packagephobia.now.sh/result?p=conventional-commits-parser) than what `semantic-release` uses.

**Comment by Aghassi** [comment]
If we could get a plugin like https://github.com/semantic-release/exec, it would help for transitioning to this system. I have some bash scripts I want to run after auto runs, but as part of auto's "pipeline". I can shim it for now, but it's a call out none the less :)

**Comment by hipstersmoothie** [comment]
Nice idea, shouldn’t be too hard. For now you could write a custom plugin
that hooks into whatever part of the process you want.

Future plugin could look like


‘’’
{
  “Plugins”: [“exec”, { “after-version”: [“echo hax0r”] }]
}
‘’’

**Comment by hipstersmoothie** [comment]
@Aghassi done 😄
