### ISSUE TITLE
SCM Support

### ISSUE THREAD

**Issue by regicsolutions** [intuit/auto#1789]
**Is your feature request related to a problem? Please describe.**

Looking to understand which GIT based SCM systems auto supports, is Bitbucket Server Supported?

**Comment by hipstersmoothie** [comment]
Currently auto and it's plugins are very tied to github. But I think it should be somewhat possible to refactor auto to have SCM plugins

**Comment by regicsolutions** [comment]
Does auto use a git client like isomorphic-git or a GitHub specific client ?https://github.com/isomorphic-git/isomorphic-git
