### ISSUE TITLE
"afterChangelog" link in hooks listing is broken

### ISSUE THREAD

**Issue by jwodder** [intuit/auto#1795]
In the list of hooks at the top of [this page](https://intuit.github.io/auto/docs/plugins/release-lifecycle-hooks), the "afterChanglog" link goes nowhere.  Presumably, it is supposed to link to the section currently titled "afterAddToChangelog" (which auto currently does not recognize as the name of a valid hook, at least not when used in "exec").

It appears that the documentation should be corrected to change the "afterAddToChangelog" section title to "afterChangelog," and then the site generator should take care of the broken link automatically.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.16.3`](https://github.com/intuit/auto/releases/tag/v10.16.3) :rocket:

**Comment by jwodder** [comment]
The issue is back.  The only difference is that this time the hook in the list of hooks is "afterChangelog" instead of "afterChanglog", but it still goes nowhere, as the actual section title is still "afterAddToChangelog".
