### ISSUE TITLE
Default label configuration in docs is out of date

### ISSUE THREAD

**Issue by jwodder** [intuit/auto#1796]
The default label configuration given [here](https://intuit.github.io/auto/docs/configuration/autorc#labels) in the documentation lists only the labels "major", "minor", "patch", "skip-release", "release", "internal", and "documentation".  However, running `auto info -v` in a repository whose `.autorc` does not configure any labels outputs configuration that also includes the labels "tests", "dependencies", and "performance".

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.16.3`](https://github.com/intuit/auto/releases/tag/v10.16.3) :rocket:
