### ISSUE TITLE
Release label required for next?

### ISSUE THREAD

**Issue by AndrewLeedham** [intuit/auto#1830]
This is more of a question, so I didn't use the template.

When using the onlyPublishWithReleaseLabel prereleases used to release on next regardless of the label, that seems to have changed recently. I am wondering if I was relying on a bug and a prerelease label should be required. Was is the intended behaviour here?

**Comment by hipstersmoothie** [comment]
This was a recent change. With https://github.com/intuit/auto/issues/1737 we started respecting skip-release (and by extension `onlyPublishWithReleaseLabel`).

You can use the [`--force` flag/config](https://github.com/intuit/auto/pull/1776) option to ensure that next always published.

**Comment by AndrewLeedham** [comment]
Makes sense. Is it the release label that trigger it then, as aposed to prerelease?

**Comment by hipstersmoothie** [comment]
yeah it's the `release` label. `prerelease` is just used to mark PR that have been released in a prerelease

**Comment by AndrewLeedham** [comment]
Gotcha. Thanks again.
