### ISSUE TITLE
auto.git.getLatestRelease() returns first commit hash on fresh repositories without releases

### ISSUE THREAD

**Issue by sentony93** [intuit/auto#1852]
**Describe the bug**

`getLatestRelease()` on a repository without any releases returns the first commit hash of the repo

**To Reproduce**

call `auto.git.getLatestRelease()` on a new repo before any full publish

**Expected behavior**

I believe it's supposed to return 0.0.0

**Environment information:**

```
Environment Information:

"auto" version: v10.18.3
"git"  version: v2.28.0
"node" version: v12.19.0
GHE version:    v2.19.3

```

**Comment by hipstersmoothie** [comment]
That is how that function should behave. I think there was something else going on. If anyone bumps into this issue again I will reopen this
