### ISSUE TITLE
10.18.3 --preid argument change with hyphen prefix breaking the build

### ISSUE THREAD

**Issue by vincentbriglia** [intuit/auto#1863]
**Describe the bug**

Since version 10.18.3, the "prefix with hyphen" change gives us the following error: 

Error: Running command 'npx' with args [lerna, publish, prepatch, --dist-tag, canary, --registry, https://npm.pkg.github.com/, --yes, --no-git-reset, --no-git-tag-version, --exact, --preid, -canary.a32c940, --loglevel, silly] failed

ERR! lerna Not enough arguments following: preid

**To Reproduce**

❌ 10.18.4 https://github.com/LEGO/klik/runs/2086202712
✅ 10.18.2 https://github.com/LEGO/klik/runs/2086294938

**Expected behavior**

I think preid doesn't understand that the next line is an argument, instead it feels like it thinks it's a command line options.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.18.6`](https://github.com/intuit/auto/releases/tag/v10.18.6) :rocket:
