### ISSUE TITLE
Wrong display of a commit message in slack

### ISSUE THREAD

**Issue by myndelx** [intuit/auto#1886]
Hey there!

If I have a commit message starting like this: `[Button] Fix something`, the slack plugin will try to display the commit message as a link instead of pure text. Here is an example of how it's rendered:

![image](https://user-images.githubusercontent.com/13200484/111187402-3c777000-85b4-11eb-8950-948ae2defd4a.png)

On the changelog or GitHub release, everything is fine.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.20.4`](https://github.com/intuit/auto/releases/tag/v10.20.4) :rocket:
