### ISSUE TITLE
Release not created, when expected to have a release created

### ISSUE THREAD

**Issue by vincentbriglia** [intuit/auto#1910]
**Describe the bug**

using conventional commits, with a few fixes, features and chores - a release doesn't get created.

**To Reproduce**

https://github.com/LEGO/klik/runs/2169371508

**Expected behavior**

Creating releases is sometimes unpredictable. 

**Screenshots**

![image](https://user-images.githubusercontent.com/452811/112048966-37fb0c00-8b0c-11eb-8738-476f59af454e.png)

**Environment information:**

```txt

```

**Additional context**

**Comment by hipstersmoothie** [comment]
Looks like this happened because of the conventional commits plugin counting `chore:` as a `skip` release. I've opened [this pr](https://github.com/intuit/auto/pull/1911) to enable configuration of this behavior

**Comment by vincentbriglia** [comment]
so if there are say 10 commits in my PR, 9 are "fix" and 1 is "chore" ... it finds a chore and then skips ?
with the behavior in the PR, that means that 10 chores would essentially create a release ?

would it make more sense to change our workflow and "squash" our commits?

**Comment by vincentbriglia** [comment]
I created an extra PR and merged it into main https://github.com/LEGO/klik/runs/2170303293 and then it caught all commits, so there is something not "correct". is it perhaps just the last commit that is taken into consideration?

**Comment by hipstersmoothie** [comment]
I think what you want is this https://github.com/intuit/auto/pull/1723 with a little more logic around a set of conventional commits. I'll do some testing on your repo and see what I find

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.22.0`](https://github.com/intuit/auto/releases/tag/v10.22.0) :rocket:

**Comment by vincentbriglia** [comment]
I think the behavior I'm after is "do commits since last release for a package contain any fix or feat, make a release accordingly. if only chores, ignore"

**Comment by vincentbriglia** [comment]
> I think what you want is this #1723 with a little more logic around a set of conventional commits. I'll do some testing on your repo and see what I find

I think you're right, let me know how i can help

**Comment by hipstersmoothie** [comment]
Finally taking a look at this. Sorry for the delay

**Comment by hipstersmoothie** [comment]
Just want to be clear: 

- You _aren't_ asking for each conventional commit to be in the changelog
- You are asking for a change to the conventional-commits plugin that takes into account all the conventional commits in a PR to determine the releaseType for that PR

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.23.0`](https://github.com/intuit/auto/releases/tag/v10.23.0) :rocket:
