### ISSUE TITLE
Request to target a specific commit for a github release

### ISSUE THREAD

**Issue by arical** [intuit/auto#1917]
Hello 👋,

Have just started using auto and it looks fantastic so far! Thank you for the great project 😄.

We're having one issue though. Auto is creating the Github release against HEAD, instead of the commit we're actually deploying. 

This works if you're creating a release for every pull request, but that's not always the case for us and potentially others. Sometimes there might be a commit or two that are in master that we're not releasing yet (they're in our stage environment, waiting for the next release). But when the Github release is created, the tag is always against HEAD.

**Context**
We're using auto `v10.22.0` with `git-tag`
We use `auto release --to ${commit_hash}` in our build pipeline when we're ready to ship changes to production.

**Describe the solution you'd like**
Ideally, when calling `release` if you pass in `--to`, that would be passed to Githubs `createRelease` [method](https://github.com/intuit/auto/blob/6505c79a96e132f5f657d694cfcf385a8f513576/packages/core/src/git.ts#L851-L858). This could override the `target_commitish` to create the release off the specified version.

It could be an additional flag, but it consistent to limit the release tag if you were already limiting the commit range using `--to`.

Apologies if this has been brought up before, I couldn't find any older issues or discussions on it.  

Thoughts?

**Comment by hipstersmoothie** [comment]
I'd be fine with adding something like that. The `release` command expects that the release has already been tagged and pushed to GitHub. GitHub defaults to tagging the HEAD of the repo is a release is created for a tag that doesn't exists. Before adding the flag do you think that you might be able to change your workflow to add the correct tag?

**Comment by arical** [comment]
Ahh, thank you! That'll be the missing piece of the puzzle.  I'll update our workflow to get us moving again, but I still think it would be a tidy addition if `release` did that automatically.

Unless I've missed a command (quite likely), we'll need to make sure our build pipeline has the correct git permissions, generate a version number, create and push the tag, then call release.

If `release` passed through the option we'd only have one line to handle all of that 😄.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.24.0`](https://github.com/intuit/auto/releases/tag/v10.24.0) :rocket:
