### ISSUE TITLE
NPM Plugin with lerna requires yarn installed globally

### ISSUE THREAD

**Issue by sethomas** [intuit/auto#1933]
**Describe the bug**

When `yarn` is NOT installed on computer (old man here using `npm`) while using the NPM plugin with mono repo via lerna, the below lines error out :

https://github.com/intuit/auto/blob/v10.24.1/plugins/npm/src/index.ts#L382
https://github.com/intuit/auto/blob/v10.24.1/plugins/npm/src/index.ts#L691
https://github.com/intuit/auto/blob/v10.24.1/plugins/npm/src/index.ts#L839

Is there a reason not to use `npx`? Or is the expectation to use `auto` is having `yarn` installed?

I see `npx` being used [here](https://github.com/intuit/auto/blob/v10.24.1/plugins/npm/src/index.ts#L911) so why both?

**To Reproduce**

1) ensure `yarn` is NOT installed on your machine
1) setup `auto` with a mono-repo with lerna
1) run `auto shipit`
1) will get [this](https://github.com/intuit/auto/blob/v10.24.1/plugins/npm/src/index.ts#L694) error

But the actual error is around `yarn` not being installed.

**Expected behavior**

No dependency on `yarn` being globally installed.

**Comment by zephraph** [comment]
Ahh, yep, I think we'd noticed this earlier and meant to change it but didn't get around to it. Thanks for the report @sethomas, it shouldn't be dependent on yarn.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.24.3`](https://github.com/intuit/auto/releases/tag/v10.24.3) :rocket:
