### ISSUE TITLE
Slack plugin no longer displays PR's or authors

### ISSUE THREAD

**Issue by kharrop** [intuit/auto#1940]
**Describe the bug**

The Slackbot only announces the new release version and does **NOT** link to the release notes, and the `atTarget` is not included in the message.

**To Reproduce**

**Expected behavior**

- Tagged slack group
- Link to release notes
- PR type (Bug, enhancement, documentation, etc)
- List of packages impacted (if applicable)
- PR title
- Authors

![image](https://user-images.githubusercontent.com/24794756/114756263-2c23f380-9d20-11eb-9078-1a2b69545c87.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/24794756/114755874-c0418b00-9d1f-11eb-9416-58e972010af6.png)

**Environment information:**

```txt

```

**Additional context**

It looks like it stopped working after this change: https://github.com/intuit/auto/commit/f494c7a16bd4c8a8a1d1f6a763a4c76ba9d4e63f#diff-51bda7738d903d4212d97ccd3a4ab545408bd37fa9d28cba0b067b63ef8796e7R381

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.27.1`](https://github.com/intuit/auto/releases/tag/v10.27.1) :rocket:
