### ISSUE TITLE
Documentation refers to afterChangelog hook using old name

### ISSUE THREAD

**Issue by jwodder** [intuit/auto#1945]
[The documentation for Release Lifecycle Hooks](https://intuit.github.io/auto/docs/plugins/release-lifecycle-hooks) lists an "afterAddToChangelog" hook.  However, this hook [was renamed in v10.0.0](https://github.com/intuit/auto/blob/main/CHANGELOG.md#v1000-thu-oct-29-2020) to just "afterChangelog".

**Comment by hipstersmoothie** [comment]
Could you submit a or with the change?

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.25.2`](https://github.com/intuit/auto/releases/tag/v10.25.2) :rocket:
