### ISSUE TITLE
auto bot

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#195]
Make a bot like semantic releases 

- posts comments on PRs and Issues with what version a change was released in 
- Set this as the default git author?

**Comment by zephraph** [comment]
A bot would be great, but it's also a bit of a heavy lift. There's gonna be a lot that goes into that. Maybe just having that as an automatic (or configurable) step at the end of `shipit` would make sense.

**Comment by hipstersmoothie** [comment]
From what it look like it could just be a github user the semantic-release team made and they use that as their default git user. kinda like how you guys have an artsy account. bot might not be the best name.

**Comment by hipstersmoothie** [comment]
#250 covers the comment part.
