### ISSUE TITLE
Rename npm package from "auto-release-cli" to just "auto"

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#196]
I just got control of the npm package name "auto" so think we are gonna switch over to that. This will make `npx` a little cleaner and make it easier to install. 

I will probably do this this weekend.

Any thoughts? @adierkens @orta @zephraph 

TODO:

- [ ] rename github project
- [ ] change the pacakge.json github repo
- [ ] deprecate "auto-release-cli" on npm
- [ ] change logo
- [ ] update getting started
- [ ] replace all instances of "auto-release" to "auto" in code and docs

**Comment by orta** [comment]
do it, we just moved most of our auto usage to one place anyway. It's totally net positive IMO.

https://github.com/artsy/orbs/blob/master/src/yarn/yarn.yml#L128-L132

**Comment by hipstersmoothie** [comment]
That line is actually what prompted me to contact the previous owner of "auto"!

**Comment by zephraph** [comment]
Yep, I’m all for it 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hipstersmoothie** [comment]
That is a good question. IDK really. Let's vote 😄 

/polls 'Release as 1.0.0' 'Major' 'Minor' 'Patch'

**Comment by hipstersmoothie** [comment]
/polls 'Release as 1.0.0' Major Minor Patch

**Comment by zephraph** [comment]
I don't know that it matters too much 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hipstersmoothie** [comment]
After sleeping on it we can't go back to 1.0.0 because we would get tag conflicts. So I think major is the best going forward

**Comment by orta** [comment]
Sure, major seems reasonable then to me

**Comment by zephraph** [comment]
Yep, I came to that same conclusion after thinking about it a bit. Going back in versions would make github releases all whack.
