### ISSUE TITLE
No assets uploaded for latest release

### ISSUE THREAD

**Issue by jwodder** [intuit/auto#1990]
The latest release of `auto` ([v10.29.0](https://github.com/intuit/auto/releases/tag/v10.29.0)) currently does not have any built assets uploaded for it.  This is breaking our CI.

**Comment by zephraph** [comment]
Ooof, thanks for the report. I'll take a look until @hipstersmoothie comes online.

**Comment by zephraph** [comment]
It looks like this is because the last full release of `main` failed: https://app.circleci.com/pipelines/github/intuit/auto/6333/workflows/07f1ae02-87af-414a-8e63-a3710d526dae/jobs/24269

**Comment by hipstersmoothie** [comment]
Should be fixed now
