### ISSUE TITLE
--owner and --repo options are useless?

### ISSUE THREAD

**Issue by jwodder** [intuit/auto#2004]
Running, say, `auto --owner intuit --repo auto version` (auto v10.29.2) when not in a Git repository fails with:

```
fatal: not a git repository (or any of the parent directories): .git
✖  error     Cannot find project owner and repository name!

You must do one of the following: 

- configure the repo for your package manager (ex: set "repository" in package.json)
- configure your git remote 'origin' to point to your project on GitHub.
```

I was under the impression that the `--owner` and `--repo` options took care of specifying the GitHub repository so that one didn't need to be in a local clone.  If that's not what they do, then what are they for?

**Comment by hipstersmoothie** [comment]
Auto needs a full git repo on the system to work. Those are some of the first flags in auto and are there just because they are config options and we try to keep config options and flags 1:1. But you're right them seem relatively useless otherwise
