### ISSUE TITLE
Highlight (or at least don't collapse) default label configuration in Docu

### ISSUE THREAD

**Issue by AndreasWeichselbaum** [intuit/auto#2015]
**Describe the bug**

The default label configuration in https://intuit.github.io/auto/docs/configuration/autorc is collapsed and very difficult to find. I was looking for it for quite some time, before finding it. I presume this is information many users will look for, so it would be preferable to highlight this information more.

**To Reproduce**
* Navigate to https://intuit.github.io/auto/docs/configuration/autorc
* Look (closely) to find the default label configuration
* Hint: search for "default label configuration"

**Expected behavior**
Default label should be expanded by default and/or have its own heading

**Screenshot**

![Screenshot 2021-06-16 at 08-36-37 `auto` Configuration File](https://user-images.githubusercontent.com/65903773/122169994-59a32f80-ce7e-11eb-913e-977a8d818327.png)

```txt

```

**Additional context**

**Comment by hipstersmoothie** [comment]
Good catch. Would you mind making a PR to update the docs?

**Comment by AndreasWeichselbaum** [comment]
> Good catch. Would you mind making a PR to update the docs?

Done: https://github.com/intuit/auto/pull/2060 @hipstersmoothie

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v10.32.4`](https://github.com/intuit/auto/releases/tag/v10.32.4) :rocket:
