### ISSUE TITLE
Is it possible to apply a semver tag, update changelog and package.json but not release?

### ISSUE THREAD

**Issue by kunalnagar** [intuit/auto#2026]
**Describe the bug**

I'm not really sure if it's a bug, but more of a question. I have a scenario where I apply a semver label (major/minor/patch) to a PR and I don't want `auto` to perform a release (to npm), yet update the `CHANGELOG.md` and `package.json` when the PR is merged. Is this possible?

I've tried multiple permutations and combinations of the semver tag and the `release`, `skip-release` and `skip` labels. It does not seem to work.

I set up a test repository here and have been [playing around](https://github.com/kunalnagar/test-auto/pulls?q=is%3Apr+is%3Aclosed) with this combination. Thank you!

**Comment by hipstersmoothie** [comment]
The closest you could get without writing a tiny plugin is: use the git-tag plugin instead of npm. this will do everything auto does but doesn't utilize the package.json at all. 

To get the package.json version to manually update it when you want to make a release
