### ISSUE TITLE
auto changelog --skip-commit

### ISSUE THREAD

**Issue by travis-crowder-kr** [intuit/auto#2070]
There is no way to stop `auto changelog` from creating a commit. In edge cases, it would be helpful to be able to optionally disable the commit feature.

**Comment by athityakumar** [comment]
@travis-crowder-kr - So, the changelog file would be generated in the CI/CD runtime, but not actually get committed to the master/release branch on merging a PR to master/release branch?

**Comment by athityakumar** [comment]
@hipstersmoothie - If this `--skip-commit` flag looks good to you, maybe we can add the `hacktoberfest` label and open it up for folks? I'd love to make a contribution 🎉

**Comment by athityakumar** [comment]
@travis-crowder-kr - I see that `noCommit` is already a boolean flag in the `changelog` command: https://github.com/intuit/auto/blob/main/packages/core/src/auto-args.ts#L79

Can you please check if `auto changelog --no-commit` works for you? I can update the GH docs if it works out of the box.

**Comment by hipstersmoothie** [comment]
You should be able to use `--dry-run` to skip the commit
