### ISSUE TITLE
Auto plugin pr-body-labels not clearing up the labels

### ISSUE THREAD

**Issue by mariadb-PrabodhMeshram** [intuit/auto#2097]
**Describe the bug**
I am using the `pr-body-plugins` in my project. It works great reading checks from body when running the GitHub action, and applies labels appropriately.
Now the problem I am facing is, when I flip some flags. Like making a major release major to minor. Or tagging a change type from `tests` to `enhancements` or any other checkbox.
The new workflow running the pr-check adds new labels to my PR all fines, but it doesn't cleans up the existing labels which it should and can cause release discrepancies.

**To Reproduce**

* Create a PR
* Add PR body with auto understandable checks
* Post creation of PR, check either release type from range of labels `bugfix`, `breaking`, `dependencies` etc.
* Run the github action with the command `auto pr-check`
* Post execution see the label updated to PR as per your choice
* Now change the release type to anything other than your last choice
* Run the github action with the command `auto pr-check`
* Post execution see new label added to the PR, but the old one is also there.

**Expected behavior**

When you select a new check, the job should clear up what is not applicable and remove old ones that are no more relevant, and should apply the latest one.

**Screenshots**

Selected `performance` and `patch`
![image](https://user-images.githubusercontent.com/91866192/138447690-ac8da6f6-7516-4e0a-9acd-1f1218db0ff1.png)

Later selected `dependencies` and `major`
![image](https://user-images.githubusercontent.com/91866192/138447895-49ce4a86-bbad-4add-a517-e170c6aa6ae4.png)

As per screenshot new choices label are up, but old one still lingering around.

**Environment information:**

```txt
Environment Information:

"auto" version: v10.32.1
"git"  version: v2.30.1 (Apple Git-130)
"node" version: v14.18.1

Project Information:

✔ Repository:      mariadb-PrabodhMeshram/setup-auto
✔ Author Name:     Prabodh Meshram
✔ Author Email:    prabodh.meshram@mariadb.com
✔ Current Version: v3.1.0
✔ Latest Release:  v3.1.0

✔ Labels configured on GitHub project

GitHub Token Information:

✔ Token:            [Token starting with ghp_]
✔ Repo Permission:  admin
✔ User:             mariadb-PrabodhMeshram
✔ API:
✔ Enabled Scopes:   repo, workflow, write:packages
✔ Rate Limit:       4990/5000
```

**Comment by intuit-svc** [comment]
:rocket: Issue was released in [`v10.36.2`](https://github.com/intuit/auto/releases/tag/v10.36.2) :rocket:
