### ISSUE TITLE
Question: Can we use auto with gitflow model branching?

### ISSUE THREAD

**Issue by bitabs** [intuit/auto#2100]
I have a project which I would like to open-source soon. I wanted to have a git-flow model workflow and work with branches, and also automate releases:

```
master -> anything merged to this branch will trigger a release (x.x.x)
hotfix -> anything merged to this branch should trigger a pre-release (e.g x.x.x-hotfix.x)
release -> anything merged to this branch should trigger a pre-release (e.g x.x.x-alpha.x)
develop -> anything merged to this branch should trigger a pre-release (e.g x.x.x-beta.x)
feature -> no release
```

I came across `@auto` which is exactly what I need for automating releases with CI/CD (CircleCI). However, I'm finding it hard to understand/integrate `auto` with git-flow workflow.

So ultimately my question is, can auto be used with git-flow model workflow?

Thanks 🙏

**Comment by hipstersmoothie** [comment]
So right now auto doesn't support hot fixes #1054 but you could get the rest working by configuring [prerelease branches](https://intuit.github.io/auto/docs/generated/shipit#prereleases). I don't think any additional setup would be needed for `feature` branch. auto would just treat that as a normal branch and do nothing
