### ISSUE TITLE
Fatal: Tag already exists

### ISSUE THREAD

**Issue by TheCapedBaldi** [intuit/auto#2125]
Not sure if this is a bug or I'm doing something wrong. I merged a PR to our pre-release branch called `beta-test` with the PR label as `patch`. However, the `auto shipit` failed with the following log:

<img width="1652" alt="Screenshot 2021-12-23 at 11 55 15" src="https://user-images.githubusercontent.com/16179773/147237512-4f34930f-3684-423d-b253-338e4d990ebd.png">

I tried deleting the `@tl-prisma/client@1.1.2-beta-test.0` tag manually and restarted my CI, however, the same error is persistent.

My thinking is that the tag already exists in our artifactory

I guess the question is, what happens in a situation where the tag already exists? Shouldn't `auto` automatically calculate the next version?

Thanks 🙏

**Comment by hscheuerle** [comment]
Did you delete the tag locally and on the remote?

**Comment by TheCapedBaldi** [comment]
Closing this ticket since the tag had to also be deleted from JFrog.
