### ISSUE TITLE
omit-release-notes not excluding pull requests with git-tag

### ISSUE THREAD

**Issue by plofty** [intuit/auto#2145]
**Describe the bug**

Created a pull request that I would like to exclude from the release notes. But it does not exclude the pull request when I create the release notes.

I have the following configured in .autorc

```txt
{
  "plugins": [
    "git-tag",
    "all-contributors",
    "first-time-contributor",
    [
      "omit-release-notes",
      {
        "username":"LOFPETER",
        "name": "Peter Loftus",
        "email": ["lofpeter@example.com"],
        "labels": "skip-test"
      }
    ]
  ],
  "owner": "LOFPETER",
  "repo": "release",
  "name": "Peter Loftus",
  "email": "lofpeter@example.com"
}
```

**To Reproduce**

1) Download auto binary
2) Set up .autorc config using git-tag plugin and add omit-release-notes section.
3) Create a branch from main and make a change
4) Create a pull request that includes a tag to skip not exclude this PR.
5) Merge Pull Request
6) Tag a release
7) Run "auto release"

Pull request is included in release notes.

**Expected behavior**

Pull Request should be excluded from release notes

**Screenshots**

**Environment information:**

```txt
Environment Information:

"auto" version: v10.32.4
"git"  version: v2.34.1
"node" version: v12.18.1
GHE version:    v2.22.26.ext

```

**Additional context**

**Comment by hipstersmoothie** [comment]
You're trying to omit a certain item from the changelog which is a little different from the [Release Notes](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes) feature.

What you are looking for is the [omit commits plugin](https://intuit.github.io/auto/docs/generated/omit-commits) this will omit the commit from both the changelog and release calculation
