### ISSUE TITLE
Gem canary hook does not respect releaseCommand

### ISSUE THREAD

**Issue by isaachinman** [intuit/auto#2148]
**Describe the bug**

The gem plugin optionally takes a `releaseCommand` config option, and does indeed [take it into consideration in the main publish hook](https://github.com/intuit/auto/blob/v10.28.0/plugins/gem/src/index.ts#L182).

However, in the canary hook, [only the default command is ever run](https://github.com/intuit/auto/blob/v10.28.0/plugins/gem/src/index.ts#L151), and `releaseCommand` is not checked.

I believe this is a clear bug and should be an easy fix – please let me know if a PR would be accepted. Thanks!

**To Reproduce**

#### `.autorc`

```json
{
  "plugins": [
    [
      "gem",
      {
        "releaseCommand": "gem push"
      }
    ]
  ],
}
```

**Comment by intuit-svc** [comment]
:rocket: Issue was released in [`v10.36.4`](https://github.com/intuit/auto/releases/tag/v10.36.4) :rocket:
