### ISSUE TITLE
[Question] Why multiple package managers plugins are incompatible between them ?

### ISSUE THREAD

**Issue by jBouyoud** [intuit/auto#2168]
# Question

According to your documentation, multiple package manager are incompatible between them.

https://intuit.github.io/auto/docs/configuration/plugins#defaults

> For the majority of "package manager" plugins you should only use one at a time. Using multiple will lead to undesired results.

Could you explain why this is required ? 

# Context

We'll try to release a multi-technologies project for exemple a micro service with : 
- a lerna structure and packages to publish contains (micro-service client API)
- A Docker image; 
- An helm chart for his infra purpose.

Where a single consistent version for all of these assets make sense. 

# Alternatives

* semantic-release : https://github.com/semantic-release/semantic-release (but commit based instead of pr-based)

# Proposition

Plugins incompatibility seems come from the `git commit/tag` and version computation on each of them.

Maybe re-integrating version computation and git commit/tag on core bundle may helps to solve this. Each plugin can give file(s) to add in release commit with hooks result.

Of course this is a huge change ;-) . 

I stay available to exchange and provide you more context if needed.

**Comment by laughedelic** [comment]
Related discussions:
- https://github.com/intuit/auto/issues/917
  > In my opinion the publish hook should really only publish for the given package manager, not create commits or push git tags. If each publishing plugin can focus only on implementation of its package manager specifics, common parts of the process can be reused and/or shared
	
- https://github.com/intuit/auto/discussions/1965
  > I need to publish two different kinds of artifacts from the same project (not npm, not a monorepo), versioning is simple and is based on git tags and git describe (for canaries), so I don't really need publishing plugins and would be happy with the git-tag plugin, if the functionality described above was supported: bump version, create tag, do my custom publishing, push the tag, publish GitHub release, etc.
  >
  > Having this would actually eliminate the need to write plugins for those use-cases where there is no manifest file with the version value: sbt, Docker, GitHub Actions, custom artifact upload, etc.

**Comment by jBouyoud** [comment]
Thanks. I didn't see the discutions 🙈 . I close this and will take a look at these discutions
