### ISSUE TITLE
Handling of repos without a release

### ISSUE THREAD

**Issue by aleclarson** [intuit/auto#222]
When a repository has no releases, no changelog should be generated. All that `auto-release` needs to do is take the version in `package.json` and perform a release with it. If the repository owner wants a changelog (for example, if they are migrating an existing repository), they should ensure the proper tags and Github releases are present before performing a release.

This will make it easier for new repositories to get started with `auto-release`. 🎉

**Comment by aleclarson** [comment]
> So when making the first release no changelog should be made? This is interesting, from my view I would want whatever feature/bug to be included in the release notes.

Think of a repository with a single `init` commit. Technically, there are no changes, as this is the first commit ever. Currently, the only problem is that category of repository is required to create a Github release and tag before they can use `auto-release`. Or at least, that's how I understand it.

**Comment by hipstersmoothie** [comment]
In that case we should be falling back to the first commit SHA https://github.com/intuit/auto-release/blob/3d495f0af69c07a30884fa05903bd2824c13d1fa/src/git.ts#L118

**Comment by aleclarson** [comment]
Yes, I'm aware of that line. Are you implying a Github release and a tag are _not_ required for repositories with a single commit? Do you agree that a changelog is pointless when a repository has no existing Github releases?

**Comment by aleclarson** [comment]
> > Are you implying a Github release and a tag are not required for repositories with a single commit?
> 
> yes. have you encountered problems around this?

I *was* getting an error when running `auto version` in such a repository, but it seems to have been fixed. The docs are rather misleading about this, too. Maybe this special case should be mentioned.

> > Do you agree that a changelog is pointless when a repository has no existing Github releases?
> 
> No. Currently the changelog reflects the release notes. You would expect the first release to have some notes right? It changed from nothing to something after all.

In my mind, a changelog is only useful for changes __between__ releases. I've never asked myself "what changed between the initial release and before it existed?" but maybe I'm missing something. 🤔

**Comment by hipstersmoothie** [comment]
> I was getting an error when running auto version in such a repository, but it seems to have been fixed. 

this was an error in the NPM plugin i fixed recently I'm pretty sure.

> The docs are rather misleading about this, too. Maybe this special case should be mentioned.

Feel free to try to make the docs clearer! 

> The docs are rather misleading about this, too. Maybe this special case should be mentioned.

`shipit` will always bump your package.json version. under the hood it runs `auto version` and passes the result to `npm version`, so a bump happens no matter what

**Comment by aleclarson** [comment]
I don't think `shipit` should bump the version when there are no existing releases. Thoughts?

**Comment by hipstersmoothie** [comment]
That's would be simple to implement. The only thing that bothers me is that you would then have to ignore whatever version you are trying to bump to

1. merge `major` PR
2. `shipit` runs and detects no published version
3. ignore label and just release whatever is in the package.json

To me it's seems like a user wouldn't want their SEMVER label ignored

**Comment by aleclarson** [comment]
Yeah, maybe we should just recommend that unreleased repositories use `npm publish` manually for the first version. Or just don't bump the version for the first release if no PRs exist yet?
