### ISSUE TITLE
Auto release fails due to denied permission on creting the commit for the changelog

### ISSUE THREAD

**Issue by smoia** [intuit/auto#2266]
**Describe the bug**

I've been running auto for a while on my packages, but lately I have an issue with the action:
It seems to be failing to commit to master to update the changelog.

It started happening when I added a couple of other actions in the same workflow, namely some style checks and changes (isort, black - it's a python project).

I checked whether changing personal token solved the problem, but it does not.
[Here's the action report](https://github.com/MIPLabCH/nigsp/actions/runs/3218892047/jobs/5265597120), followed by [the workflow itself](https://github.com/MIPLabCH/nigsp/blob/master/.github/workflows/auto-release.yml).

I download a packaged version of auto, my former token had the permissions `admin:public_key, repo, user, workflow, write:packages`, and my new one has `project, repo, user, write:discussion, write:packages`.

I'm in doubt on how to solve this...

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment information:**

```txt

```

**Additional context**

**Comment by ccremer** [comment]
I was able to solve this, for anyone stumbling across the same issue.

The key is to tell the [checkout action](https://github.com/actions/checkout) that we want another token, especially since by default the checkout actions stores the default GH token, which is insufficient for pushing commits. Here's an example workflow snippet:
```yaml
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          token: ${{ secrets.RELEASE_TOKEN }} # your PAT
```

**Comment by hipstersmoothie** [comment]
@ccremer Would you mind submitting a PR to the actions docs?

**Comment by ccremer** [comment]
@hipstersmoothie done, see #2366
