### ISSUE TITLE
Ignore labels

### ISSUE THREAD

**Issue by alexec** [intuit/auto#2287]
I want auto to ignore labels completely and always release a minor version.

Why? Engineers make too many mistakes with labels. The automation tooling tries to apply labels, but gets it wrong.

Fixing this problem results in around 2h lost engineering time per incident. Happen to my team about twice a week. Multiply by engineering teams and projects O(n^3) engineering cost? This could create a $3m annual cost?

I work at Intuit.

**Comment by sugarmanz** [comment]
Hey Alex, just override the labels in your autorc to meet your needs:
https://intuit.github.io/auto/docs/configuration/autorc#overriding-default-labels

If you only ever want to release minors, only specify a minor label and
mark it as default.

**Comment by sugarmanz** [comment]
You'll need the `noDefaultLabels` option too:

```json
{
  "noDefaultLabels": true,
  "labels": [
    { "releaseType": "minor", "name": "Version: Minor", "default": true }
  ]
}
```
