### ISSUE TITLE
[QUESTION] Does it work with pnpm workspaces/turborepo/nx?

### ISSUE THREAD

**Issue by AlexandrosMelissas** [intuit/auto#2342]
Does it version individual apps or packages of a monorepo handled by pnpm workspaces or turborepo or nx? I manage a monorepo with turborepo and everytime i try to `auto shipit`, it versions my project root e.x. v1.0.1 etc. How can i have tagging such as app1@1.0.1, app2@1.1.2, package1@1.0.1 ? Is there any workflow i am missing? or it only works with monorepos handled by lerna?

**Comment by jdalrymple** [comment]
Have you seen this? https://github.com/waldronmatt/pnpm-turborepo-auto-boilerplate

**Comment by jdalrymple** [comment]
You only need the lerna.json/peer dep, you dont need to use lerna for your monorepo in general. I use nx for gitbeaker without any issue. To get the independent versioning you need to set the version key in your lerna.json to `independent`.

**Comment by AlexandrosMelissas** [comment]
Tbh i didn't really know you could use lerna like that since i've never used it before. I have spent days trying to have conventional commits in monorepo. I'm gonna try it out. Thank you for taking me in the right direction.

**Comment by jdalrymple** [comment]
hahah no worries, I've been there. Feel free to follow up if you have questions
