### ISSUE TITLE
v11.1.3 Release is missing assets

### ISSUE THREAD

**Issue by nick-seward** [intuit/auto#2450]
**Describe the bug**

The v11.1.3 release page - https://github.com/intuit/auto/releases/tag/v11.1.3

There are only 2 assets on that page. Both are compressed source code artifacts. A zip and a tar.gz.
There's no MacOS or Windows binary.

When trying to update Auto via Homebrew, users get a 404 error because of the missing assset. 
```sh
==> Fetching intuit/auto/auto
==> Downloading https://github.com/intuit/auto/releases/download/v11.1.3/auto-macos.gz
curl: (22) The requested URL returned error: 404                                                                                            

Error: auto: Failed to download resource "auto"
Download failed: https://github.com/intuit/auto/releases/download/v11.1.3/auto-macos.gz
```

Contrast this with v11.1.2 which has assets for different platforms, https://github.com/intuit/auto/releases/tag/v11.1.2

**To Reproduce**

Broken download link for MacOS - https://github.com/intuit/auto/releases/download/v11.1.3/auto-macos.gz

**Expected behavior**

No broken links.

**Screenshots**

**Environment information:**

```txt

```

**Additional context**

**Comment by nick-seward** [comment]
This could be the cause - https://github.com/intuit/auto/actions/runs/8546831136/job/23418507248#step:7:7859

A failed release step in the CI/CD pipeline./

**Comment by lsojka-kroger** [comment]
@hipstersmoothie 
Any chance for a quick fix for this failed release? 
Thanks in advance!

**Comment by hipstersmoothie** [comment]
Looking into this now

**Comment by lsojka-kroger** [comment]
Thank you @hipstersmoothie!!
