### ISSUE TITLE
Release changlog should show full PR title when it contains & (ampersand)

### ISSUE THREAD

**Issue by MrHash** [intuit/auto#2460]
**Describe the bug**

PR title is missing in release changelog when the title contains square brackets.

**To Reproduce**

Run shipit to create a release from a squash merge containing a conventional or other commit followed by square brackets: e.g. `fix: [ref-xzy] fixing thing & other`

The release changelog shows: `fix: #prnumber (author)`

**Expected behavior**

The release changelog should show: `fix: [ref-xzy] fixing a thing & other #prnumber (author)`

**Additional context**

**Comment by sammieboy97** [comment]
Hi @MrHash, If this is not worked upon right now, I can take it up.

**Comment by tlkiong** [comment]
@MrHash  can you share your config or even better a minimally repo that reproduce the issue?
Mine is showing `fix: [ref-xzy] fixing a thing & other #prnumber (author)` with zero configuration

**Comment by MrHash** [comment]
here's the .autorc
```
{
  "plugins": [
    "git-tag",
    "conventional-commits",
    "first-time-contributor"
  ],
  "shipit": {
    "noChangelog": true
  }
}
```

**Comment by tlkiong** [comment]
just to debug a bit.
What if you remove:
```
"shipit": {
  "noChangelog": true
}
```

**Comment by MrHash** [comment]
nothing really, that just disables creation of changelog file in root, not the release notes. maybe you can adjust the tests

**Comment by MrHash** [comment]
TBH this is an old issue, i'm not sure if it's valid anymore. I think best to close until i see it again. thanks anyway
