### ISSUE TITLE
Init hooks

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#254]
**Is your feature request related to a problem? Please describe.**

hooks during `init` so `released` plugin can add a default label for `create-labels`

**Comment by hipstersmoothie** [comment]
Making the `labels` tappable in `loadConfig` could probably meet `create-label`s needs

**Comment by zephraph** [comment]
Yep, makes sense.

**Comment by adierkens** [comment]
:rocket: Issue was released in v4.6.0 :rocket:
