### ISSUE TITLE
Released label added twice

### ISSUE THREAD

**Issue by zephraph** [intuit/auto#281]
**Describe the bug**

For some reason we occasionally see doubled up release labels. 

https://github.com/artsy/palette/pulls?q=is%3Apr+is%3Aclosed

I'm not exactly sure _why_ it happens. Doesn't look like it's happened to all PRs. It's not a huge issue in general, but something I just happened to notice. 

**Expected behavior**

Only one released label

**Screenshots**

![image](https://user-images.githubusercontent.com/3087225/52160277-790bda00-2680-11e9-91b5-b18b35150cab.png)

**Comment by adierkens** [comment]
:rocket: Issue was released in v4.8.6 :rocket:
