### ISSUE TITLE
auto pr-check exposes token on some failures

### ISSUE THREAD

**Issue by zephraph** [intuit/auto#296]
**Describe the bug**

I had an incident today where `auto check-pr` made a call (trying to post a status) via `octokit` that resulted in a 404 error. This caused an exception that wasn't caught and ended up printing the response object in our CI log (which is public).

Feel free to reach out to me for the specific example. I think I have a general idea of how to go about solving this, so I'll start a PR and see where it goes. 

I also opened https://github.com/octokit/rest.js/issues/1246 because it'd really be ideal for this to be handled there so we don't have to play whack-a-mole with potential security issues. 

**Expected behavior**

`auth` header should never be included in a response or error object.

**Comment by adierkens** [comment]
:rocket: Issue was released in v4.8.11 :rocket:
