### ISSUE TITLE
Add `clear` option for `auto comment`

### ISSUE THREAD

**Issue by adierkens** [intuit/auto#308]
We use `auto comment` to post stuff back to a PR (deployed URLs, performance results, etc). 

Successive builds will overwrite the old comment (delete and re-add but that's fine), but I'd like a way to delete the old comment at the start of a new build. That way stale info about deployments/testing isn't kept around in the event of a build failure. 

I would imagine it would be a flag in place of `--message`, maybe `--delete` or `-d`. If supplied (and no `--message` is present) we would delete the existing message w/ the same `context`, and not post a new one. If you pass both `--delete` and `--message` we'd do the same thing we do now (delete the old one, and post a new one)

**Comment by hipstersmoothie** [comment]
fooooo

**Comment by hipstersmoothie** [comment]
foooooo

**Comment by hipstersmoothie** [comment]
foooooo

**Comment by adierkens** [comment]
:rocket: Issue was released in v6.5.0 :rocket:
