### ISSUE TITLE
Gracefully handle rate limits

### ISSUE THREAD

**Issue by zephraph** [intuit/auto#334]
**Is your feature request related to a problem? Please describe.**

I've noticed auto [failing on rate limits](https://circleci.com/gh/artsy/renovate-config/2683) recently. It seemed strange to me since the requests are obviously happening with an authenticated user. 

The rate limits themselves were curious in that there's a limit of 30: `'x-ratelimit-limit': '30'`. 

Turns out the [search api rate limit](https://developer.github.com/v3/search/#rate-limit) is much smaller than other endpoints so we need to handle this a little more gracefully. 

**Describe the solution you'd like**

Octokit has a [throttling plugin](https://www.npmjs.com/package/@octokit/plugin-throttling) that can be used to handle rate limiting scenarios automatically. There's also a retry plugin that automatically will retry failed requests. 

You can see an [implementation](https://github.com/artsy/dupe-report/blob/515ecb1bb15c4f7533d69a8d838fb02874bc8d9d/packages/dupe-report/src/api/github.ts#L12) of this that I did in a different project. It's pretty easy to integrate. 

I'll try to tackle this this evening if I can some time.

**Comment by zephraph** [comment]
Here's a [build](https://circleci.com/gh/artsy/renovate-config/2721) with very-verbose enabled. That's a _lot_ of api calls 😅.

**Comment by adierkens** [comment]
:rocket: Issue was released in v4.9.0 :rocket:
