### ISSUE TITLE
--canary flag

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#345]
**Is your feature request related to a problem? Please describe.**

I would like to be able to release a canary version through auto on each PR.

**Describe the solution you'd like**

The ability to run:

```sh
auto shipit --canary
```

Which publishes a version like `auto@1.2.3-canary.PR_NUMBER.BUILD_NUMBER`

**Describe alternatives you've considered**

Manually running lerna or npm commands, ew. 😉

**Comment by adierkens** [comment]
:rocket: Issue was released in v4.12.0 :rocket:
