### ISSUE TITLE
Ability to publish to a `next` branch

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#346]
**Is your feature request related to a problem? Please describe.**

I would like to have a `next` branch that publishes to the `next` tag on NPM. Merges to the `next` branch should use `auto` to calculate based on the PRs merged to that branch + the last release that matches the branch name.

**Describe the solution you'd like**

Basically i should be able to:

1. merge to `next` branch
2. `auto` calculates version using only PRs merged to that branch
3. Changelog contains prerelease notes
4. publish to `next` npm label
5. Update latest `pre-release` on Github

Once merged into master prerelease changelog entries are combined into one under the final version.

The next version also should only increment by 1 of the greatest semantic release version. 

EX:

1. Starting version 1.2.3
2. PR w/minor label merged to next branch
3. Next branch version 1.3.0-next.1
4. PR w/breaking label merged to next branch 
5. Next branch version 2.0.0-next.1
6. PR w/breaking label merged to next branch 
7. Next branch version 2.0.0-next.2

EDIT:

After thinking about this more the API should look like this:

- [x] call shipit from master -> latest version released
- [x] call shipit from PR in CI -> canary version released #351
- [ ] call shipit from a prelease branch -> publish prelease version to prelease branch name tag (ex: publish next branch to next tag)

prerelease branches will be configured by the autorc. By default the only prerelease branch is `next`. prerelease branches are treated just like the master branch, but instead of publishing to latest they publish to their tag.

**Comment by hipstersmoothie** [comment]
After thinking about this more the API should look like this:

- [x] call shipit from master -> latest version released
- [ ] call shipit from PR in CI -> canary version released #351
- [ ] call shipit from a prelease branch -> publish prelease version to prelease branch name tag (ex: publish next branch to next tag)

prerelease branches will be configured by the autorc. By default the only prerelease branch is `next`. prerelease branches are treated just like the master branch, but instead of publishing to latest they publish to their tag.

**Comment by hipstersmoothie** [comment]
https://github.com/intuit/auto/issues/573#issuecomment-543307135

**Comment by athityakumar** [comment]
Hey @hipstersmoothie! 👋 

I was just going through the repo, and am pretty interested by how `auto` automates git actions. I'd love to know more about the current state of this issue, and if I can take it up for the internal Hacktoberfest. 😄

**Comment by hipstersmoothie** [comment]
This was actually an issue I plan on taking up. It's actually a pretty hard
thing to take on (I'm even a little hesitant to start). I'd be happy to
help you out with another issue. Feel free to take a stab at it if you
really want to, it just requires a lot of previous knowledge.

I feel like a few better places to start

- https://github.com/intuit/auto/issues/525 - We could really use some
documentation around usage with Github actions. This would just be another
page in the docs with sample configs. a lot like the circle one. with this
issue you could also play around with auto to see how it works more

- https://github.com/intuit/auto/issues/143 - This one could also be good.
there was some work on this before but it was unmerged so you might
reference that

- https://github.com/intuit/auto/issues/443 - Figure out how to test npx

- https://github.com/intuit/auto/issues/332 - Small update to the docs

- https://github.com/intuit/auto/issues/462 not too hard to fix bug in a
plugin

Let me know if you have any questions. And be sure to ask them in the
issues so we have a history of it.

Thanks,
Andrew

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.17.0-next.0 :rocket:

**Comment by adierkens** [comment]
:rocket: Issue was released in v8.0.0 :rocket:
