### ISSUE TITLE
Configurable base branch

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#355]
**Is your feature request related to a problem? Please describe.**

`auto shipit` is intended to be ran from the base branch and will only publish to the latest tag when on that branch. Currently, this is set to always be `master`. 

If a user changes the base branch `auto shipit` will no longer work.

**Describe the solution you'd like**

A configuration option to specify the base branch

#351

**Comment by zephraph** [comment]
This is fixed by #357
