### ISSUE TITLE
Remove the ability for auto configs to be javascript

### ISSUE THREAD

**Issue by zephraph** [intuit/auto#369]
**Is your feature request related to a problem? Please describe.**

For the last few weeks I've been thinking of what a GitHub app for auto would look like. Given the criticality of having a label (and the proper label) I think it's definitely needed. 

I hit an issue pretty early though. `auto` uses cosmic config meaning its configuration file can technically be JavaScript. Likewise, when publishing an extended config it's really just requiring the entry file from an npm package. Before I've written any other logic I'm now thinking about how I can safely execute arbitrary javascript in this GitHub app...

Now, I could dive head first down the rabbit hole of sandboxing or macgyvering some v8 isolates solution together, but the complexity of that solution vastly outweighs that of the problem I'm trying to solve. 

**Describe the solution you'd like**

I propose that we remove arbitrary code execution vulnerabilities by limiting what formats an auto config can be saved as. We can do this with the current setup by limiting the [search places](https://github.com/davidtheclark/cosmiconfig#searchplaces) and [loaders](https://github.com/davidtheclark/cosmiconfig#loaders) to exclude common.js modules. 

We would also need to update how the extended config works. This is the trickier part. We could continue with the package distribution model but look for one of the non-common.js cosmic config files in the package. The downside of this is that it makes it more difficult to have a separate auto config just for the auto-config repo... if that makes any sense.

I think it's likely that you can set the main field to point to a json file, but people might forget that set or it might be confusing. We could also just require the user to add a path to the file (i.e. `@artsy/autorc`)

[Renovate](https://renovatebot.com/docs/) actually [handles this problem](https://renovatebot.com/docs/config-presets/#preset-hosting) by requiring the extended config to be stored in the package.json. You can see ours [here](https://unpkg.com/@artsy/renovate-config@1.12.1/package.json) under the `renovate-config` key. That would simplify the handling of extended configs quite a bit. 

Lastly, we could also just add support for a URL. That might just be a good addition generally. 

**Describe alternatives you've considered**

Make no change to `auto`. Use [V8 isolates](https://github.com/laverdet/isolated-vm) to sandbox the user controlled JS execution. This means I likely wouldn't be able to go with lambda hosting (as it has a native component) and I'd have to deal with a long lived process with a bit more added up front complexity. 

I'm not _against_ doing this necessarily, but I'd just like to get the MVP of this done with as little work as possible.

**Comment by adierkens** [comment]
:rocket: Issue was released in v6.0.0 :rocket:
