### ISSUE TITLE
Add canary version to bottom of PR body. 

### ISSUE THREAD

**Issue by zephraph** [intuit/auto#376]
**Is your feature request related to a problem? Please describe.**

When a PR is published via a release it makes sense for a comment at the end of the thread to denote the version it was released in. There's likely to be no other traffic and it's easy enough to find. When using canary releases though, the releases are happening while development is still going on. Canary versions can end up sandwiched in weird places and can break up the flow of a PR. 

**Describe the solution you'd like**

Instead of adding the canary version as a comment on a PR, add it to the end of the PR body. That keeps it near the description at the top of the thread and ultimately out of the way. 

**Describe alternatives you've considered**

Thought briefly about a temporary label that would be removed after the PR is published, but that'd clutter up the label space and there's some value to having a reference to the canaries after the PR has released.

**Comment by hipstersmoothie** [comment]
@zephraph I coded something up. But I've now realized it might make more sense to do in status check at the bottom? I kind of like it being at the top though

**Comment by hipstersmoothie** [comment]
I tested it out and it seems like the status can get buried easily. PR body update seem the best. @zephraph thoughts?

**Comment by adierkens** [comment]
:rocket: Issue was released in v6.1.0 :rocket:

**Comment by zephraph** [comment]
Sorry, totally missed these. Looks good though 👍
