### ISSUE TITLE
Incorrect canary release version

### ISSUE THREAD

**Issue by egoist** [intuit/auto#381]
**Describe the bug**

**To Reproduce**

Run `auto canary --pr XXX` locally

**Actual behavior**

It seems everything after `+` is ignored

**Screenshots**

<img width="723" alt="屏幕快照 2019-05-07 下午6 50 25" src="https://user-images.githubusercontent.com/8784712/57294057-04ba5a00-70f9-11e9-967a-d02370c2d714.png">

What I get is `saber-plugin-pwa 0.1.1-canary.400` on npm

**Desktop (please complete the following information):**

**Additional context**

Auto: `6.0.2`

**Comment by adierkens** [comment]
:rocket: Issue was released in v6.1.1 :rocket:

**Comment by adierkens** [comment]
:rocket: Issue was released in v6.1.1 :rocket:
