### ISSUE TITLE
Admin acces GH_TOKEN

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#390]
Since we have started updating the PR body with the canary version that means the GH_TOKEN's user must have admin access to the repo. 

@zephraph does this change you workflow at all?

**Comment by zephraph** [comment]
This would be an interesting requirement. I don't think we've really ever tried a bot that can edit the PR body, but our bot account is just a member of the repo, not a admin.

**Comment by hipstersmoothie** [comment]
Tested and the GH_TOKEN's user only needs to be a member, adding the the pr-body doesn't require higher permissions
