### ISSUE TITLE
Conventional Commits Plugin: Respect pr label

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#462]
**Describe the bug**

i'm pretty sure right now if you label a pr with `minor` but it has a message with `fix:` it it will count as a patch:

- labels should take precedence
- if > 1 commit exists individual CC commits should get unique changelog items, along with the PR

**Comment by athityakumar** [comment]
Hey @hipstersmoothie!

I'd like to take this up. Can you guide me regarding how I can re-create this bug (like, any test that handles this), or what would be a good starting place?

**Comment by hipstersmoothie** [comment]
1. set up auto on a dummy project 
2. create a commit with commit message 'fix: something'
3. create another commit 'fix: test'
4. open a PR and label it `minor`
5. run `yarn auto changelog -d'

Result: Should have 2 changelog entries (a patch and a minor)

**Comment by athityakumar** [comment]
Gotcha, let me try this out and revert back with a query/PR! 😄

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.15.2` :rocket:
