### ISSUE TITLE
Slack message tag link repeats

### ISSUE THREAD

**Issue by hello-woof** [intuit/auto#463]
I'm using the slack plugin to post releases to a slack channel. The owner and repo name repeats in the tag link, which causes a 404 when opened.

Current: https://github.com/hello-woof/demo/hello-woof/demo/releases/tag/1.1.3
Expected: https://github.com/hello-woof/demo/releases/tag/1.1.3

![image](https://user-images.githubusercontent.com/48960849/59726422-6dabec00-91e6-11e9-8025-c72131c528e8.png)

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.1.2 :rocket:
