### ISSUE TITLE
Changelog entries sometimes blank

### ISSUE THREAD

**Issue by zephraph** [intuit/auto#503]
**Describe the bug**

I'm not sure exactly _why_ this happens, but there are times when the changelog doesn't record entries. It's weird, but auto's released plugin correctly takes the associated PRs as released, but the changelog is empty?

See [this diff](https://github.com/artsy/palette/compare/v4.14.40...v4.14.41) has an example. 

It's possible it's related to PRs being merged too fast. I'm uncertain.

**Comment by hipstersmoothie** [comment]
closing as I'm pretty sure it's fixed. Feel free to re-open if you see it happen again!
