### ISSUE TITLE
Auto using email rather than github login?

### ISSUE THREAD

**Issue by shilman** [intuit/auto#509]
**Describe the bug**

For some reason, Auto is using my github email address rather than my login. See for example:

https://github.com/storybookjs/design-system/releases/tag/v0.0.43

**To Reproduce**

Here are my settings:

```
$ git config --list | grep user
user.name=Michael Shilman
user.email=[what's in changelog]
```

The email matches my primary email address on Github. I checked with @domyen and @kylesuss, whose logins are showing up properly, and their settings are equivalent. I'm using Github Desktop with SSH auth.

To repro, run `yarn auto changelog` in the Storybook Design System: https://github.com/storybookjs/design-system

**Expected behavior**

Expect it to use my github login @shilman in the changelog entries. 

**Desktop (please complete the following information):**

- OS: MacOS 10.14.5
- Version 4.15.5

**Comment by hipstersmoothie** [comment]
Thanks for the report! I'll try to take a look this week

**Comment by shilman** [comment]
@hipstersmoothie Any luck? I'd like to write an article about using Auto in Storybook Design System but it's hard for me to recommend in the current state. If it's not obvious from the symptoms or you can't repro I'll try to debug it myself. Thanks!

**Comment by hipstersmoothie** [comment]
I’ll take a look tomorrow!

**Comment by shilman** [comment]
Thanks for looking into this @hipstersmoothie, it makes sense! Guess I need to stop cutting corners on the commits. 😭 Sorry for the fuss!
