### ISSUE TITLE
Ability to edit comments

### ISSUE THREAD

**Issue by tylerkrupicka** [intuit/auto#516]
**Is your feature request related to a problem? Please describe.**

I'd like to get an edit history of comments back to a Pull Request. The delete/add flow makes it hard to see what happened on previous commits.

**Describe the solution you'd like**

A flag of some sort for the comment plugin.

**Describe alternatives you've considered**

**Additional context**

**Comment by su7edja** [comment]
Hi @tylerkrupicka is the idea to make the default behavior be "edit" instead of delete/add when an existing context is there?

**Comment by hipstersmoothie** [comment]
Right now it will:

1. delete the old comment
2. add a new comment with the user's data

This should remain the default behavior.

This task requires:

- [ ] add a flag called `--edit, -e` that instead edits the old comment without deleting anything

**Comment by su7edja** [comment]
Sounds good. I will work on that. @hipstersmoothie can you assign this issue to me?

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.7.0 :rocket:
