### ISSUE TITLE
Running auto commands with GitHub Actions v2 (CI/CD)?

### ISSUE THREAD

**Issue by glambert** [intuit/auto#525]
**Is your feature request related to a problem? Please describe.**

Not a problem 😄 

**Describe the solution you'd like**

Have you tried using GitHub Actions CI/CD to run `auto` commands instead of let's say CircleCI?

**Describe alternatives you've considered**

CircleCI

**Additional context**

Have been trying to run our own ways of publishing (right now using only Lerna with some manual release steps) with GitHub Actions but have been struggling running workflows **only** when a new tag is created (I know this can be done with [CircleCI](https://intuit.github.io/auto/pages/circleci.html) like you mention in your docs).

**Comment by glambert** [comment]
Also, is it possible to publish private packages with Lerna and `auto`? I've been running into issues getting this to work properly.

Thanks!

**Comment by hipstersmoothie** [comment]
> Have you tried using GitHub Actions CI/CD to run auto commands instead of let's say CircleCI?

Yeah I have, it takes a little extra setup. It seems github actions aren't set up to push back to the repo from an action. Here is how I have been doing it

https://github.com/hipstersmoothie/eslint-formatter-github/blob/master/.github/workflows/push.yml#L24

> Also, is it possible to publish private packages with Lerna and auto? I've been running into issues getting this to work properly.

Like to a private registry?

To publish to a private registry you should also:

1. Set up a publishConfig at the root package.json with your registry

```json
  "publishConfig": {
    "registry": "https://registry.npmjs.YOURS.com"
  },
```

2. Add this value in your 'lerna.json`

```json
{
  "registry": "https://registry.npmjs.YOURS.com",
  "packages": [
    "packages/*"
  ],
  "version": "0.76.0",
  "npmClient": "yarn",
  "useWorkspaces": true
}
```

You might also need to set publish configs on the sub-packages as well.

**Comment by glambert** [comment]
I’ll give this a spin and report back on how it went, thanks a lot for taking the time to reply. 

Keep up the great work on auto!

**Comment by hipstersmoothie** [comment]
Added docs for github actions to the docs website. If any further assistance is needed feel free to open another issue!
