### ISSUE TITLE
Enhance options to include 'from' for 'version' and 'release' commands

### ISSUE THREAD

**Issue by bnigh** [intuit/auto#534]
**Is your feature request related to a problem? Please describe.**
- Ideally there should be a single source of truth in which the version is persisted
- auto uses github releases as source of truth
- Ideally the user should be able to specify this source of truth (ie: from git tags, package.json, ...)

**Describe the solution you'd like**
- Expand the input options for `auto version` & `auto release` commands to include a `from` option (similar to `auto changelog` command).
  - potentially other commands could include this as well
  - this way, users who don't use the `auto shipit` command, could calculate and pass the current version (before updating using auto)

**Describe alternatives you've considered**
- Hooks could be used to solve this
  - auto currently allows customization of certain fetching of versions via [getpreviousversion](https://intuit.github.io/auto/pages/writing-plugins.html#getpreviousversion) hook
    - however, `auto version` & `auto release` commands also fetch github latest release
  - the existing hook could be enhanced or a new hooks could be added, such that the user could specify how to retrieve the current / `from` version

**Additional context**
- Adding additional input options vs hooks are not mutually exclusive, and likely would be good to implement both
- I'm thinking would be best to implement additional options first, since that would allow most flexibility (user wouldn't have to modify or write a plugin to use)

**Comment by bnigh** [comment]
@hipstersmoothie Do you have any additional thoughts or alternative suggestions regarding this proposal? Otherwise, I may start looking into it this weekend. Thanks

**Comment by hipstersmoothie** [comment]
> git tag --sort=-v:refname | head -n 1

we might want to expose this functionality as an option on the git-tag plugin, seems useful

After reading your response, I agree that the `from` option should be added the the commands you listed. Makes sense and I can now see the use. Go for it!

> What is the purpose of this vs fetching latest release from github?

I am a bit fuzzy on this now, probably should have commented this code better 😅
