### ISSUE TITLE
Ability to have multiple labels map to minor, major patch

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#539]
**Is your feature request related to a problem? Please describe.**

I want to be able to create a `new-component` label that is equivalent to `minor`

**Describe the solution you'd like**

Be able to configure multiple labels for any of the semver labels, potentially all labels

**Describe alternatives you've considered**

Adding both labels, but it should be better!

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.4.0 :rocket:
