### ISSUE TITLE
Auto trust github.com

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#550]
**Is your feature request related to a problem? Please describe.**

I frequently have to add `- run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config` when setting up a new repo.

**Describe the solution you'd like**

It should do this automatically

**Comment by pabo** [comment]
Dibs. I can try to knock this out :)

**Comment by hipstersmoothie** [comment]
close via #969

#969 tries to ensure that the remote is pushable. otherwise it falls back to origin and you get the same behavior. 

In circle's case the problem was it uses ssh auth so the remote was for ssh. ssh is a little hard to set up for this (lots of step). Now it uses https://TOKEN@gi.... which will be able to push!
