### ISSUE TITLE
Duplicate released comments

### ISSUE THREAD

**Issue by zephraph** [intuit/auto#553]
**Describe the bug**

We've noticed release comments being duplicated... it may be related to forks. 

Here's the issue it happened on: https://github.com/artsy/reaction/pull/2769
Here's the CI output: https://circleci.com/gh/artsy/reaction/42804

**Comment by su7edja** [comment]
@zephraph Does this still happen? 
I tried it using forks, but I did not duplicate comments.

Could you provide the steps to reproduce this?

**Comment by zephraph** [comment]
Ahh, thanks for the ping. I haven't noticed this for a while now, I think it was fixed (or an issue with our setup).
