### ISSUE TITLE
Bundle Binary

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#62]
**Is your feature request related to a problem? Please describe.**

`auto` should be bundled as a binary so that it can be distributed and consumed by other package ecosystems. (brew, apt-get, bower, whatever java uses)

possible bundlers:

- [ncc](https://github.com/zeit/ncc)
- [parcel](https://parceljs.org/) - in node mode
- https://github.com/zeit/pkg#readme maybe this is actually what i was thinking of

need to figure out interop with plugins

**Comment by orta** [comment]
If you want a reference, Danger JS uses pkg and release-it to automatically generate and deploy to a home-brew tap: https://github.com/danger/danger-js/pull/671

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v7.0.0 :rocket:

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v7.0.0 :rocket:
