### ISSUE TITLE
How to use auto for private repo? Which Github API to use ?

### ISSUE THREAD

**Issue by yashug** [intuit/auto#627]
**Describe the bug**
Error: Error calling github: getProjectLabels

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by hipstersmoothie** [comment]
It should work normally on a private repo as long as you're using a key that has access.

Are you on a `private` repo on public github? Or is it a repo on enterprise github?

**Comment by hipstersmoothie** [comment]
@yashug I will be closing this issue Dec 12, 2019 if there are no more interactions. Debug info needed!
