### ISSUE TITLE
QUESTION: docs/examples for setup with Lerna?

### ISSUE THREAD

**Issue by jrnail23** [intuit/auto#654]
Can anyone please point me to some documentation or examples of how to use `auto` with `lerna` monorepos (particularly using `independent` versioning)?

Thanks in advance.

**Comment by hipstersmoothie** [comment]
`auto` itself is an example of using `lerna` with `auto`, although we do not use independent versioning. I have an example of what it might look like.

https://github.com/hipstersmoothie/auto-lerna-independent/

It isn't the best experience (the github releases could split up the changes more), but it works.

**Comment by hipstersmoothie** [comment]
https://github.com/intuit/auto/issues/656

**Comment by jrnail23** [comment]
thanks @hipstersmoothie, I'll dive in to that repo.

**Comment by jrnail23** [comment]
damn, I hadn't even thought about how GH releases would work... I had already decided that I'm not in love with the idea of only having a single changelog for the whole repo (I'd probably like to have a changelog for each independently versioned package), perhaps for similar reasons that complicate GH release handling.

**Comment by hipstersmoothie** [comment]
You're right that would probably be another thing we would want to handle when addressing #656. In the current state we would probably want to add the changelog to each sub-package even when not in an independant repo.

**Comment by hipstersmoothie** [comment]
https://github.com/intuit/auto/issues/657

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.15.1 :rocket:
