### ISSUE TITLE
npm: Better GitHub Releases in an `independent` lerna project

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#656]
**Is your feature request related to a problem? Please describe.**

https://github.com/hipstersmoothie/auto-lerna-independent/releases

**Describe the solution you'd like**

The changes for a package are in a release that matches.

**Describe alternatives you've considered**

This will probably require a new hook so that the `npm` plugin can take control of what gets posted in which release.

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.8.0` :rocket:

**Comment by glambert** [comment]
Nice, thanks for this @hipstersmoothie :tada:
