### ISSUE TITLE
Incorrect commit message for version bumps

### ISSUE THREAD

**Issue by jrnail23** [intuit/auto#692]
When running `auto shipit` using lerna, my commit message ends up being `Bump version to: %v [skip ci]` instead of `Bump version to: v.2.0.0 [skip ci]`

Looks like the problem is here: https://github.com/intuit/auto/blob/dbffbefcf35e902e22e654df9b28b4c7255d2599/plugins/npm/src/index.ts#L448

```js
          "'Bump version to: %v [skip ci]'",
```
should be 
```js
          '"Bump version to: %v [skip ci]"',
```
(note the first snippet has single quotes surrounded by double quotes, preventing the version from being properly interpolated)

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.15.2 :rocket:

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.15.2 :rocket:

**Comment by jrnail23** [comment]
Well damn, @hipstersmoothie, I just finally got to try this fix (#693) in anger, and it doesn't actually work.  I'm still getting `Bump version to: %v [skip ci]` as a commit message. 😕 
I guess this issue should be re-opened.

**Comment by jrnail23** [comment]
BTW, not sure if it matters, but I'm using lerna with independent package versioning.

**Comment by jrnail23** [comment]
@adierkens, @hipstersmoothie: this issue should be re-opened.  My above referenced PR didn't actually seem to fix the bug.

**Comment by hipstersmoothie** [comment]
@jrnail23 is your project and independent project?

From the lerna docs:

> Note that this placeholder interpolation only applies when using the default "fixed" versioning mode, as there is no "global" version to interpolate when versioning independently.

**Comment by hipstersmoothie** [comment]
@jrnail23 If you are in an independent project, #915 should make your commit message better.

**Comment by jrnail23** [comment]
@hipstersmoothie, beautiful... thanks a ton!

**Comment by hipstersmoothie** [comment]
You should check out the 9..8.0 release. I just made the github release
page for independent projects a whole lot better
