### ISSUE TITLE
Getting GIT error when used `auto shipit` through GitHub actions but working fine when published in local terminal

### ISSUE THREAD

**Issue by yashug** [intuit/auto#749]
On Private Repo

```
Error: Running command 'git' failed

error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/*/*'

    at ChildProcess.<anonymous> (/home/runner/work/*/*/node_modules/@auto-it/core/dist/utils/exec-promise.js:45:24)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by hipstersmoothie** [comment]
Have you followed this doc? 

https://intuit.github.io/auto/pages/build-platforms/github-actions.html

You have to do all this 

```
        run: |
          git checkout "${GITHUB_REF:11}" --
          git remote rm origin
          git remote add origin "https://$GH_TOKEN@github.com/hipstersmoothie/my-test-project"
          git fetch origin
          git branch --set-upstream-to origin/master
```

**Comment by hipstersmoothie** [comment]
@yashug has the updated docs helped?

**Comment by yashug** [comment]
@hipstersmoothie yes. But one enhancement which i needed is, after publish the new commit which involves bumping version and release notes should push to development branch rather than master branch. 

I have a development branch and master branch. whenever i want to publish new version i will merge development into master, this will trigger GitHub action to publish. But once process done the new commit should come into development branch instead master branch. how this can be achieved. This way i won't see failure action by 'skip ci' commit. Hope you got the query

**Comment by hipstersmoothie** [comment]
This is what is going out in v8. #346 It will kind of get you that workflow, but not quite.

Since you are doing a more custom release pipeline you might not want to use `shipit` since it will not deviate from our standard workflow. Instead you could use the lower level commands `version` `changelog` and `release`. 

https://intuit.github.io/auto/pages/getting-started.html#detailed-setup

> But once process done the new commit should come into development branch instead master branch. how this can be achieved.

This seems odd to me. If you created a commit for say `v1.0.0` that would have to go in the base branch.

**Comment by yashug** [comment]
@hipstersmoothie the commit going into both master and base branch. i want to avoid running github action again because of new commit into master branch. if it only commits into development branch, github action wont trigger on master branch

**Comment by glambert** [comment]
> Have you followed this doc?
> 
> https://intuit.github.io/auto/pages/build-platforms/github-actions.html
> 
> You have to do all this
> 
> ```
>         run: |
>           git checkout "${GITHUB_REF:11}" --
>           git remote rm origin
>           git remote add origin "https://$GH_TOKEN@github.com/hipstersmoothie/my-test-project"
>           git fetch origin
>           git branch --set-upstream-to origin/master
> ```

Docs are outdated compared to this example, is it intended?

```
          git remote add origin https://$<your-github-user>:GITHUB_TOKEN@github.com/<project-owner>/<project-repo>
```

**Comment by hipstersmoothie** [comment]
@zephraph recently updated those with some finding #750

**Comment by glambert** [comment]
@hipstersmoothie the updated in #750 are 👍 but are not reflected in https://intuit.github.io/auto/pages/build-platforms/github-actions.html. Are the docs published from the repo files?

**Comment by hipstersmoothie** [comment]
Ah there was another PR too

https://github.com/intuit/auto/pull/752/files
