### ISSUE TITLE
all-contributors plugin: add Renovate to excluded ones; add **/test/** as test

### ISSUE THREAD

**Issue by tunnckoCore** [intuit/auto#754]
**Is your feature request related to a problem? Please describe.**

Currently only Dependabot, Fossabot and Greenkeeper are excluded by default. I think @RenovateBot is also super widely used and I'm using it for years. 

Second, I think a `test/` directory is also commonly used so it would be good to be included by default too.

**Describe the solution you'd like**

1. add `renovate, renovate[bot], renovate-approve` to exclude list
2.  add `**/test/**` and `**/__tests__/**` to the `test: ['**/*.test.*'],` list.

**Describe alternatives you've considered**

`Auto` plugins are configurable and we can add it manually, but... both cases are commonly used so I think it's better to be included by default.

**Additional context**

No.

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.17.0 :rocket:

**Comment by adierkens** [comment]
:rocket: Issue was released in v8.0.0-next.13 :rocket:
