### ISSUE TITLE
bug: next branch adds "⚠️ Push to Master" to release notes

### ISSUE THREAD

**Issue by Aghassi** [intuit/auto#823]
**Describe the bug**

The release notes for the prerelease say "push to master" when make release notes. This is probably unnecessary or should reflect the branch name I'm pushing to (eg next/alpha/beta) depending on my configuration.

**To Reproduce**

Make a `next` branch and push directly to it

**Expected behavior**

Prerelease notes don't say "push to master" but rather the name of the prerelease I'm pushing to

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.15.5` :rocket:
