### ISSUE TITLE
feature: check if current commit is behind the branch to be published

### ISSUE THREAD

**Issue by Aghassi** [intuit/auto#825]
**Is your feature request related to a problem? Please describe.**

Right now, you need to be careful about pushing frequently because you may cause a release problem. Other libraries, such as [semantic-release](https://github.com/semantic-release/semantic-release) do a check to see if the current push is behind the branch it is about to release to. If it is behind, the release is skipped and left up to the next commit to deploy. Ideally, auto can do the same thing so we can avoid the worry of "timing commits"

**Describe the solution you'd like**

Pretty much do this before the run starts but after the tokens are verified https://github.com/semantic-release/semantic-release/blob/b2b7b57fbd51af3fe25accdd6cd8499beb9005e5/lib/git.js#L179

**Describe alternatives you've considered**

Telling my team not to push as frequently, but that doesn't help when we use thing like Renovate which can auto merge things for us.

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.16.0` :rocket:
