### ISSUE TITLE
Next channels cause an `@channel` release note with slack plugin

### ISSUE THREAD

**Issue by Aghassi** [intuit/auto#828]
**Describe the bug**

If you use the `next` feature, the slack plugin will post to your slack channel with an `@channel` by default. This may make sense on the baseBranch, but it doesn't make sense from a preview branch (in my opinion). It can be confusing for developers, and particularly annoying if you have hundreds of users in a channel.

**To Reproduce**

Trigger a `next` tag to release with the slack plugin added to your auto config.

**Expected behavior**

I believe by default the `next` release should *not* cause a slack release, and have it opt-in.

**Comment by hipstersmoothie** [comment]
fixed via #829
