### ISSUE TITLE
Custom plugin with malformed syntax throws error for file not found

### ISSUE THREAD

**Issue by Aghassi** [intuit/auto#841]
**Describe the bug**

If you are creating a plugin that has a problem executing (in my case, I had a problem where my prototype chain was wrong) `auto` said it "could not find plugin for file path path/to/file". From a debugging standpoint, this was quite confusing because the file did exist on disk.

**To Reproduce**

Write a plugin where you check a prototype chain that is wrong or doesn't exist

**Expected behavior**

Auto should say it can't load a plugin because the plugin threw an error or was malformed

**Comment by adierkens** [comment]
:rocket: Issue was released in v9.3.1 :rocket:
