### ISSUE TITLE
auto version - error on missing PRs in a forked repo

### ISSUE THREAD

**Issue by divyavanmahajan** [intuit/auto#857]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

As a quick and dirty workaround, I patched the @auto-it/core/dist/release.js (about line 405)
Replace the next line 
>    const info = await this.git.getPr(modifiedCommit.pullRequest.number);

with
>   let info = null; try {info=await this.git.getPr(modifiedCommit.pullRequest.number);} catch {}
      
Using sed
> sed -i bak "s/const info = await this.git.getPr(modifiedCommit.pullRequest.number);/ let info = null; try {info=await this.git.getPr(modifiedCommit.pullRequest.number);} catch {}/" node_modules/@auto-it/core/dist/release.js

**Comment by adierkens** [comment]
:rocket: Issue was released in v9.0.1 :rocket:
