### ISSUE TITLE
Auto release is failing on  repository without tags 

### ISSUE THREAD

**Issue by ncheema** [intuit/auto#886]
**Describe the bug**
(related to : https://github.com/intuit/auto/issues/554)
Executing `auto shipit` on repo with no  tags causes the following exceptions. _Temp fix is to manually add a tag to the repo._ 
```text
Error: Running command 'git' with args [describe, --tags, --abbrev=0, ] failed
fatal: No names found, cannot describe anything.
    at ChildProcess.child.on.code (/snapshot/auto/node_modules/@auto-it/core/dist/utils/exec-promise.js:49:24)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
   script returned exit code 1
```

**To Reproduce**

- A project without tags
- with following plugin: plugins: ["git-tag"]
- execute `auto shipit`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by adierkens** [comment]
:rocket: Issue was released in v9.2.1 :rocket:
