### ISSUE TITLE
Add docs warning about merging too quickly

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#91]
**Is your feature request related to a problem? Please describe.**

document the perils of merging too quickly

**Comment by hipstersmoothie** [comment]
Possible solution to this discussed with @adierkens:

Set a status on all open PRs to fail while release is in progress. This way a user cannot merge until this status turns green. 

Kinda weird but would fix the problem

**Comment by zephraph** [comment]
That's certainly one solution. I'm trying to handle this at the CI level by queuing master builds. Unfortunately Circle doesn't provide a native mechanism for this, but @eddiewebb created an orb to handle it. 

You can checkout [reaction](https://github.com/artsy/reaction/blob/master/.circleci/config.yml#L46) to see our setup. I'm not 100% certain that it solves the problem (especially if instead of checking out master the steps are checking out a hash) but I hope it gets us close.

**Comment by adierkens** [comment]
If you queue the master build you run into the issue where you're first CI build of master makes commits on top of the stuff that's already been merged (to bump versions) -- or could hit merge conflicts in the release.

Not sure if there's a clean way of doing it

**Comment by hipstersmoothie** [comment]
Also:

1. Merge PR 1 with `patch` label
2. Merge PR 2 with `minor` label
3. CI runs and calculates a `minor` bump and includes both PRs
4. CI runs again and publishes a `patch` with no changes

Should be:

1. Merge PR 1 with `patch` label
2. Merge PR 2 with `minor` label
3. CI runs and calculates a `patch` bump and includes only PR 1
4. CI runs and calculates a `minor` bump and includes only PR 2

**Comment by aleclarson** [comment]
Can auto-release not release multiple versions in a single CI build?

**Comment by hipstersmoothie** [comment]
Maybe, the problem is a lot of this behavior is CI dependent and `auto` doesn't interact with the CI it just runs on it.

**Comment by aleclarson** [comment]
I was thinking in the context of Travis CI specifically, where pushing interrupts the current build. In that case, `auto-release` should be able to detect that the `patch` PR was merged before the `minor` PR and appropriately perform two releases as expected. AFAICT, this behavior wouldn't conflict with other CI services that don't interrupt the current build on push.

**Comment by hipstersmoothie** [comment]
The case where "minor before patch" is more important though. if the `minor` is the first PR we need to respect that label more. 

But re-reading what you want is on the second CI run detect the interrupted run and perform two separate `shipit`s for each release, regardless of release type. Am i correct?

**Comment by adierkens** [comment]
:rocket: Issue was released in v7.15.1 :rocket:
