### ISSUE TITLE
Maven release multiple tags for the same release

### ISSUE THREAD

**Issue by ncheema** [intuit/auto#926]
**Describe the bug**
Given release `1.0.0`, during the maven plugin release we create tag  `v1.0.0`. However during the post step in `auto.loadDefaultBehavior` auto pushes release notes to tag `1.0.0`. This is due to `newVersion` missing the prefix. We can fix this in maven plugin by overriding new version post maven release execution. 
https://github.com/intuit/auto/blob/master/plugins/maven/src/index.ts#L141-L142
``` javascript
await execPromise('mvn', [
        '-B',
        'release:prepare',
        `-Dtag=v${newVersion}`,
        `-DreleaseVersion=${newVersion}`,
        '-DpushChanges=false'
      ]);
```

**To Reproduce**

execute maven plugins, it will result in two tags for the same release. `v1.0.0`, `1.0.0`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.8.4` :rocket:
