### ISSUE TITLE
Allow command flags to be configured from autorc

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#999]
**Is your feature request related to a problem? Please describe.**

I want to permanently enable some flag for an `auto` command

**Describe the solution you'd like**

**`.autorc`**

```jsonc
{
  // Configure any of auto's commands
  "release": {
    // Prerelease will always be true unless the --prerelease flag is provided
    "prerelease": true
  }
}
```

**Additional context**

This will also solve for forcing canaries in #993. With this new type of configuration a user could provide the following to always have canaries, whether or not they're made through the `canary` or `shipit` command.

```json
{
  "canary": {
    "force": true
  }
}
```

**Comment by adierkens** [comment]
:rocket: Issue was released in `v9.15.0` :rocket:
